import { requireAdmin } from '@/lib/auth';
import { recentAdminAudit } from '@/lib/security';
import { listBusinesses } from '@/lib/store';
import { Building2, ExternalLink, Plus, ShieldCheck, Store, CreditCard, CircleCheck, CirclePause, Clock3 } from 'lucide-react';
import { listActorSessions } from '@/lib/auth-store';
import SessionSecurityCard from '@/components/SessionSecurityCard';
import DashboardShell from '@/components/DashboardShell';
import { billingStatusLabel } from '@/lib/billing';
export const dynamic='force-dynamic';

export default async function AdminPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const adminSession=await requireAdmin();
 const [salons,auditRows,sessions]=await Promise.all([listBusinesses(),recentAdminAudit(30),listActorSessions('admin',adminSession.sub)]);
 const q=await searchParams;
 return <DashboardShell role="admin" name={adminSession.name||'Admin'} businessName="Rezix Control Center">
  <section id="overview" className="dashboard-hero"><div><span className="eyebrow">REZIX CONTROL CENTER</span><h1>Salonverwaltung</h1><p>Salons, Tarife und Zugänge zentral verwalten.</p></div><div className="role-status"><ShieldCheck size={15}/> System Admin · v0.8.3</div></section>
  <div className="metrics dashboard-metrics"><Metric label="Salons gesamt" value={String(salons.length)} icon={<Store/>}/><Metric label="Aktive Salons" value={String(salons.filter(s=>s.active).length)} icon={<CircleCheck/>}/><Metric label="Free Trial" value={String(salons.filter(s=>s.subscriptionStatus==='trialing').length)} icon={<Clock3/>}/><Metric label="Bezahlte Tarife" value={String(salons.filter(s=>s.billingPlan!=='trial').length)} icon={<CreditCard/>}/></div>
  {q.created&&<div className="success">Salon wurde erfolgreich erstellt.</div>}{q.mailError&&<div className="alert">Salon erstellt, aber die Verifizierungs-E-Mail konnte nicht versendet werden.</div>}{q.error&&<div className="alert">Salon konnte nicht erstellt werden. Prüfe die Eingaben.</div>}{q.upload&&<div className="alert">Bild-Upload fehlgeschlagen. Prüfe Storage und Dateigröße.</div>}
  <div className="dashboard-section-grid admin-dashboard-grid">
   <section id="new-salon" className="panel"><div className="section-kicker">NEUER SALON</div><h2><Plus size={20}/> Salon registrieren</h2><p className="muted">Logo und Stempel: PNG, JPG oder WEBP bis 2 MB.</p>
    <form className="stack-form" method="post" action="/api/admin/business/create" encType="multipart/form-data"><label>Salonname</label><input name="name" placeholder="z. B. Royal Cuts" required/><label>URL-Kürzel (Slug)</label><input name="slug" placeholder="royal-cuts" pattern="[a-zA-Z0-9äöüÄÖÜß -]+" required/><small className="muted">Öffentliche Karte: /s/royal-cuts</small><div className="form-split"><div><label>Stempelziel</label><input name="rewardTarget" type="number" min="2" max="30" defaultValue="10" required/></div><div><label>Belohnung</label><input name="rewardText" defaultValue="Ein kostenloser Haarschnitt" required/></div></div><label>Salon Logo</label><input name="logo" type="file" accept="image/png,image/jpeg,image/webp" required/><label>Eigener Stempel</label><input name="stamp" type="file" accept="image/png,image/jpeg,image/webp" required/><hr/><h3>Manager-Zugang</h3><label>Name des Managers</label><input name="managerName" required/><label>E-Mail des Managers</label><input name="managerEmail" type="email" required/><label>Temporäres Passwort</label><input name="managerPassword" type="password" minLength={12} required/><button className="gold" type="submit">Salon erstellen</button></form>
   </section>
   <section id="salons" className="panel"><div className="panel-head"><div><div className="section-kicker">SALONS</div><h2><Store size={20}/> Registrierte Salons</h2><p className="muted">Kundendaten bleiben ausschließlich im Manager-Bereich des jeweiligen Salons.</p></div><span className="admin-salon-count">{salons.length} Salons</span></div>{salons.length===0?<div className="empty-block"><Building2 size={36}/><b>Noch keine Salons</b><span>Lege links den ersten Salon an.</span></div>:<div className="salon-list">{salons.map(s=>{const plan=planLabel(s.billingPlan);const trial=trialText(s.trialEndsAt,s.subscriptionStatus);return <div className="salon-row admin-salon-row" key={s.id}>{s.logoUrl?<img className="salon-logo" src={s.logoUrl} alt=""/>:<div className="salon-logo placeholder"><Store/></div>}<div className="salon-meta"><div className="salon-title-line"><b>{s.name}</b><span className={`salon-state ${s.active?'is-active':'is-disabled'}`}>{s.active?<><CircleCheck size={12}/> Aktiv</>:<><CirclePause size={12}/> Gesperrt</>}</span></div><span>/s/{s.slug}</span><small>{s.rewardTarget} Stempel · {s.rewardText}</small><div className="salon-badges"><span className={`plan-badge plan-${s.billingPlan}`}><CreditCard size={12}/>{plan}</span><span className={`subscription-badge sub-${s.subscriptionStatus}`}>{billingStatusLabel(s.subscriptionStatus)}</span>{trial&&<span className="trial-remaining"><Clock3 size={12}/>{trial}</span>}</div></div><a className="icon-link" href={`/s/${s.slug}`} target="_blank" rel="noreferrer"><ExternalLink size={18}/></a></div>})}</div>}</section>
  </div>
  <section id="system" className="dashboard-section"><div className="section-heading"><div><span className="section-kicker">SYSTEM</span><h2>Sicherheit & Sitzungen</h2></div></div><SessionSecurityCard sessions={sessions} currentJti={adminSession.jti} revoked={!!q.sessionsRevoked}/><div className="panel quick" style={{marginTop:16}}><h2>Admin Audit</h2>{auditRows.length===0?<div className="empty-block"><ShieldCheck size={30}/><b>Noch keine Ereignisse</b></div>:<div className="attention">{auditRows.slice(0,12).map((a:any,i:number)=><div className="row" key={`${a.created_at}-${i}`}><div className="avatar sm"><ShieldCheck size={15}/></div><div><b>{auditLabel(String(a.action))}</b><span>{new Date(a.created_at).toLocaleString('de-DE')}</span></div></div>)}</div>}</div></section>
 </DashboardShell>;
}
function Metric({label,value,icon}:{label:string,value:string,icon:React.ReactNode}){return <div className="metric"><div className="iconbox">{icon}</div><span>{label}</span><b>{value}</b><small>Live</small></div>}
function auditLabel(a:string){const m:Record<string,string>={'auth.login.success':'Anmeldung erfolgreich','auth.login.failed':'Anmeldung fehlgeschlagen','auth.logout':'Abmeldung','friseur.created':'Friseur-Zugang erstellt','stamp.added':'Stempel hinzugefügt','stamp.failed.not_found':'Ungültiger Kundencode','kunde.registered':'Kunde registriert','business.created':'Salon erstellt','billing.checkout.created':'Zahlung gestartet','billing.checkout.failed':'Zahlung fehlgeschlagen','billing.portal.opened':'Zahlungsportal geöffnet'};return m[a]||a}

function planLabel(plan:string){const m:Record<string,string>={trial:'Free Trial',starter:'Starter',professional:'Professional',business:'Business'};return m[plan]||plan}
function trialText(endsAt:string|null,status:string){if(status!=='trialing'||!endsAt)return null;const ms=new Date(endsAt).getTime()-Date.now();if(ms<=0)return 'Trial beendet';const days=Math.max(1,Math.ceil(ms/86400000));return `${days} Tag${days===1?'':'e'} übrig`}
