import { requireAdmin } from '@/lib/auth';
import { recentAdminAudit } from '@/lib/security';
import { listBusinesses } from '@/lib/store';
import { Building2, ExternalLink, Plus, ShieldCheck, Store, Users, CreditCard, CircleCheck, CirclePause, Clock3 } from 'lucide-react';
import { listActorSessions } from '@/lib/auth-store';
import SessionSecurityCard from '@/components/SessionSecurityCard';
import { billingStatusLabel } from '@/lib/billing';
export const dynamic='force-dynamic';
export default async function AdminPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const adminSession=await requireAdmin(); const [salons,auditRows,sessions]=await Promise.all([listBusinesses(),recentAdminAudit(30),listActorSessions('admin',adminSession.sub)]); const q=await searchParams;
  return <main><header className="topbar"><div className="brand"><img src="/icon.svg" alt="Rezix"/><div><b>REZIX</b><span>ADMIN</span></div></div><form method="post" action="/api/logout"><button type="submit" className="secondary">Abmelden</button></form></header>
  <div className="shell"><div className="page-title"><div><span className="eyebrow">REZIX CONTROL CENTER</span><h1>Salonverwaltung</h1><p>Salons anlegen, Branding definieren und den ersten Manager-Zugang erstellen.</p></div><div className="pill"><ShieldCheck size={15}/> System Admin</div></div>
  {q.created&&<div className="success">Salon wurde erfolgreich erstellt. Der Manager erhält eine E-Mail zur Bestätigung.</div>}{q.mailError&&<div className="alert">Der Salon wurde erstellt, aber die Verifizierungs-E-Mail konnte nicht versendet werden. Prüfe die E-Mail-Konfiguration.</div>}{q.error&&<div className="alert">Salon konnte nicht erstellt werden. Prüfe alle Angaben und ob E-Mail/Slug bereits existieren.</div>}{q.upload&&<div className="alert">Bild-Upload fehlgeschlagen. Prüfe Supabase Storage Variablen und Dateigröße.</div>}
  <div className="owner-grid"><section className="panel"><h2><Plus size={20}/> Neuen Salon registrieren</h2><p className="muted">Logo und Stempel werden im Rezix Storage gespeichert. Maximal 2 MB pro Bild.</p>
  <form className="stack-form" method="post" action="/api/admin/business/create" encType="multipart/form-data">
  <label>Salonname</label><input name="name" placeholder="z. B. Royal Cuts" required/>
  <label>URL-Kürzel (Slug)</label><input name="slug" placeholder="royal-cuts" pattern="[a-zA-Z0-9äöüÄÖÜß -]+" required/><small className="muted">Öffentliche Karte: /s/royal-cuts</small>
  <div className="form-split"><div><label>Stempelziel</label><input name="rewardTarget" type="number" min="2" max="30" defaultValue="10" required/></div><div><label>Belohnung</label><input name="rewardText" defaultValue="Ein kostenloser Haarschnitt" required/></div></div>
  <label>Salon Logo</label><input name="logo" type="file" accept="image/png,image/jpeg,image/webp" required/>
  <label>Eigener Stempel</label><input name="stamp" type="file" accept="image/png,image/jpeg,image/webp" required/>
  <hr/><h3>Manager-Zugang</h3><label>Name des Managers</label><input name="managerName" required/><label>E-Mail des Managers</label><input name="managerEmail" type="email" required/><label>Temporäres Passwort</label><input name="managerPassword" type="password" minLength={12} required/>
  <button className="gold" type="submit">Salon erstellen</button></form></section>
  <section className="panel"><div className="panel-head"><div><h2><Store size={20}/> Registrierte Salons</h2><p className="muted">Hier werden ausschließlich Salons angezeigt. Kundendaten sind nur im jeweiligen Manager-Bereich sichtbar.</p></div><span className="admin-salon-count">{salons.length} Salons</span></div>{salons.length===0?<div className="empty-block"><Building2 size={36}/><b>Noch keine Salons</b><span>Der erste Salon wird über das Formular links erstellt.</span></div>:<div className="salon-list">{salons.map(s=>{const plan=planLabel(s.billingPlan);const trial=trialText(s.trialEndsAt,s.subscriptionStatus);return <div className="salon-row admin-salon-row" key={s.id}>{s.logoUrl?<img className="salon-logo" src={s.logoUrl} alt=""/>:<div className="salon-logo placeholder"><Store/></div>}<div className="salon-meta"><div className="salon-title-line"><b>{s.name}</b><span className={`salon-state ${s.active?'is-active':'is-disabled'}`}>{s.active?<><CircleCheck size={12}/> Aktiv</>:<><CirclePause size={12}/> Gesperrt</>}</span></div><span>/s/{s.slug}</span><small>{s.rewardTarget} Stempel · {s.rewardText}</small><div className="salon-badges"><span className={`plan-badge plan-${s.billingPlan}`}><CreditCard size={12}/>{plan}</span><span className={`subscription-badge sub-${s.subscriptionStatus}`}>{billingStatusLabel(s.subscriptionStatus)}</span>{trial&&<span className="trial-remaining"><Clock3 size={12}/>{trial}</span>}</div></div><a className="icon-link" href={`/s/${s.slug}`} target="_blank" rel="noreferrer" title="Kundenseite öffnen"><ExternalLink size={18}/></a></div>})}</div>}</section></div>
  <section className="panel quick"><h2>Systemübersicht</h2><div className="quick-grid"><Info icon={<Store/>} title="Salons gesamt" text={String(salons.length)}/><Info icon={<CircleCheck/>} title="Aktive Salons" text={String(salons.filter(s=>s.active).length)}/><Info icon={<Clock3/>} title="Free Trial" text={String(salons.filter(s=>s.subscriptionStatus==='trialing').length)}/></div></section><SessionSecurityCard sessions={sessions} currentJti={adminSession.jti} revoked={!!q.sessionsRevoked}/><section className="panel quick"><h2>Security Audit</h2>{auditRows.length===0?<div className="empty-block"><ShieldCheck size={30}/><b>Noch keine Ereignisse</b><span>Security-Aktionen erscheinen hier automatisch.</span></div>:<div className="attention">{auditRows.map((a:any,i:number)=><div className="row" key={`${a.created_at}-${i}`}><div className="avatar sm"><ShieldCheck size={15}/></div><div><b>{auditLabel(String(a.action))}</b><span>{String(a.actor_type).toUpperCase()} · {a.business_id?`Salon ${String(a.business_id).slice(0,12)}`:'System'} · {new Date(a.created_at).toLocaleString('de-DE')}</span></div></div>)}</div>}</section></div></main>
}
function Info({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="info"><div className="iconbox">{icon}</div><div><b>{title}</b><span>{text}</span></div></div>}

function auditLabel(a:string){const m:Record<string,string>={'auth.login.success':'Anmeldung erfolgreich','auth.login.failed':'Anmeldung fehlgeschlagen','auth.logout':'Abmeldung','friseur.created':'Friseur-Zugang erstellt','stamp.added':'Stempel hinzugefügt','stamp.failed.not_found':'Ungültiger Kundencode','kunde.registered':'Kunde registriert','business.created':'Salon erstellt','billing.checkout.created':'Stripe Checkout erstellt','billing.checkout.failed':'Stripe Checkout fehlgeschlagen','billing.portal.opened':'Stripe Kundenportal geöffnet'};return m[a]||a}

function planLabel(plan:string){const m:Record<string,string>={trial:'Free Trial',starter:'Starter',professional:'Professional',business:'Business'};return m[plan]||plan}
function trialText(endsAt:string|null,status:string){if(status!=='trialing'||!endsAt)return null;const ms=new Date(endsAt).getTime()-Date.now();if(ms<=0)return 'Trial beendet';const days=Math.max(1,Math.ceil(ms/86400000));return `${days} Tag${days===1?'':'e'} übrig`}
