const {test}=require('node:test');const assert=require('node:assert/strict');const load=require('./load-typescript.cjs');
function fixture(){let saved;let uploads=0;const {POST}=load('app/api/manager/loyalty-config/route.ts',{
 '@/lib/billing':{billingOperational:()=>true},'next/server':{NextResponse:{redirect:(url,status)=>new Response(null,{status,headers:{location:String(url)}}),json:(body,opts)=>Response.json(body,opts)}},
 '@/lib/auth':{currentSession:async()=>({role:'manager',businessId:'salon-a'})},
 '@/lib/store':{getBusinessById:async()=>({slug:'salon-a',customerDesign:{imageUrl:'https://storage.example/old.png'}}),updateBusinessCardConfig:async x=>{saved=x;}},
 '@/lib/storage':{uploadSalonAsset:async()=>{uploads++;return 'https://storage.example/new.png';}},'@/lib/security':{sameOrigin:()=>true,audit:async()=>{}}
 });return {POST,saved:()=>saved,uploads:()=>uploads};}
function request(patch={},design=true){const f=new FormData();const values={rewardTarget:'10',rewardText:'Reward',cardTitle:'Card',cardSubtitle:'Welcome',primaryColor:'#2563EB',stampShape:'circle',...(design?{backgroundMode:'gradient',backgroundColor:'#FFFFFF',gradientColor:'#DBEAFE',backgroundOverlay:'0.25',backgroundPosition:'top',backgroundSize:'cover'}:{}),...patch};for(const [k,v]of Object.entries(values))f.set(k,v);return new Request('https://example.test/api/manager/loyalty-config',{method:'POST',body:f});}
test('design save keeps existing image and targets the current manager salon',async()=>{const f=fixture();const r=await f.POST(request());assert.equal(r.status,303);assert.match(r.headers.get('location'),/configSaved/);assert.equal(f.saved().businessId,'salon-a');assert.equal(f.saved().customerDesign.imageUrl,'https://storage.example/old.png');assert.equal(f.saved().customerDesign.overlay,.25);});
test('invalid background settings do not upload or save',async()=>{for(const patch of [{backgroundOverlay:'2'},{backgroundPosition:'left'},{backgroundColor:'url(evil)'},{backgroundSize:'bad'}]){const f=fixture();const r=await f.POST(request(patch));assert.match(r.headers.get('location'),/configError/);assert.equal(f.saved(),undefined);assert.equal(f.uploads(),0);}});
test('legacy card submissions leave background unchanged; removal is explicit',async()=>{const f=fixture();await f.POST(request({},false));assert.equal(f.saved().customerDesign,undefined);await f.POST(request({removeBackground:'on'}));assert.equal(f.saved().customerDesign.imageUrl,null);});

test('uploaded background replaces the saved image',async()=>{const f=fixture();const r=await f.POST(request({backgroundMode:'image',background:new File(['mock-image'],'background.png',{type:'image/png'})}));assert.match(r.headers.get('location'),/configSaved/);assert.equal(f.uploads(),1);assert.equal(f.saved().customerDesign.imageUrl,'https://storage.example/new.png');});

test('transparent panel and typography are saved with the customer design',async()=>{const f=fixture();await f.POST(request({panelOpacity:'0',textColor:'#FFFFFF',headingColor:'#DBEAFE',mutedColor:'#ABCDEF',fontFamily:'serif',fontStyle:'italic',fontWeight:'600',fontSize:'18',headingSize:'32'}));const d=f.saved().customerDesign;assert.equal(d.panelOpacity,0);assert.equal(d.fontFamily,'serif');assert.equal(d.headingSize,32);assert.equal(d.textColor,'#FFFFFF');});
test('invalid typography is rejected before saving',async()=>{for(const patch of [{panelOpacity:'2'},{fontSize:'100'},{headingSize:'0'},{fontFamily:'url(evil)'},{textColor:'red;display:none'},{fontStyle:'bad'}]){const f=fixture();const r=await f.POST(request(patch));assert.match(r.headers.get('location'),/configError/);assert.equal(f.saved(),undefined);}});
