const {test}=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const load=require('./load-typescript.cjs');
function storeFixture(){const queries=[];const tag=async(strings,...values)=>{queries.push({sql:strings.join('?'),values});if(strings.join('').includes('from businesses'))return [{id:'salon',created_at:new Date(),active:true}];return [{count:7}];};const store=load('lib/store.ts',{'./customer-design':load('lib/customer-design.ts'),'./db':{database:()=>tag},'./billing':{}});return {store,queries};}
test('designer loads only its business; customer page keeps pagination and count',async()=>{const f=storeFixture();await f.store.getDashboardData('salon',1,'loyalty');assert.equal(f.queries.length,1);f.queries.length=0;const data=await f.store.getDashboardData('salon',3,'customers');assert.equal(f.queries.length,3);assert.equal(data.totalCustomers,7);assert.equal(f.queries.find(q=>q.sql.includes('offset')).values[1],50);assert.ok(f.queries.every(q=>q.values[0]==='salon'));});
test('async password verification supports current and legacy hashes and rejects wrong passwords',async()=>{const {store}=storeFixture();const promise=store.hashPassword('test-password');assert.equal(typeof promise.then,'function');const p=await promise;assert.equal(await store.verifyPassword('test-password',p.salt,p.hash),true);assert.equal(await store.verifyPassword('wrong',p.salt,p.hash),false);const salt='ab'.repeat(16);const legacy=crypto.pbkdf2Sync('legacy',Buffer.from(salt,'hex'),210000,32,'sha256').toString('hex');assert.equal(await store.verifyPassword('legacy',salt,legacy),true);assert.equal(await store.verifyPassword('wrong',salt,legacy),false);});
const keys=crypto.generateKeyPairSync('rsa',{modulusLength:2048});
const env={GOOGLE_WALLET_ENABLED:'true',GOOGLE_WALLET_ISSUER_ID:'12345',GOOGLE_WALLET_CLIENT_EMAIL:'wallet@example.test',GOOGLE_WALLET_KEY_BASE64:Buffer.from(keys.privateKey.export({type:'pkcs8',format:'pem'})).toString('base64'),NEXT_PUBLIC_APP_URL:'https://example.test',SUPABASE_URL:'https://storage.test'};
const google=load('lib/google-wallet.ts',{},env);
const business={id:'a',name:'Salon A',slug:'salon-a',logoUrl:null,cardTitle:'Meine Karte',primaryColor:'#123456',customerDesign:{mode:'color',color:'#334455'}};
const customer={id:'member',name:'Test Member',code:'RZX-12345678'};
test('Google passes have a valid RSA signature and separate identities per tenant',()=>{const link=google.createGoogleWalletLink(business,customer);const parts=link.split('/').at(-1).split('.');assert.equal(crypto.verify('RSA-SHA256',Buffer.from(parts[0]+'.'+parts[1]),keys.publicKey,Buffer.from(parts[2],'base64url')),true);const claims=JSON.parse(Buffer.from(parts[1],'base64url'));assert.equal(claims.payload.genericObjects[0].barcode.value,customer.code);assert.equal(claims.payload.genericObjects[0].hexBackgroundColor,'#334455');const other=google.googleWalletPayload({...business,id:'b'},customer);assert.notEqual(other.genericObjects[0].id,claims.payload.genericObjects[0].id);assert.notEqual(other.genericClasses[0].id,claims.payload.genericClasses[0].id);assert.equal(JSON.stringify(claims).includes('private_key'),false);});
test('unconfigured Google Wallet refuses issuance',()=>{assert.throws(()=>load('lib/google-wallet.ts',{},{}).createGoogleWalletLink(business,customer));});
test('Windows PFX accepts matching private key and rejects wrong password or certificate-only files',()=>{const forge=require('node-forge');const pair=forge.pki.rsa.generateKeyPair(1024);const cert=forge.pki.createCertificate();cert.publicKey=pair.publicKey;cert.serialNumber='01';cert.validity.notBefore=new Date();cert.validity.notAfter=new Date(Date.now()+86400000);cert.setSubject([{name:'commonName',value:'Test'}]);cert.setIssuer(cert.subject.attributes);cert.sign(pair.privateKey);const encode=(key)=>Buffer.from(forge.asn1.toDer(forge.pkcs12.toPkcs12Asn1(key,[cert],'test-password',{algorithm:'3des'})).getBytes(),'binary').toString('base64');const apple=load('lib/apple-wallet.ts',{});const decoded=apple.readPfx(encode(pair.privateKey),'test-password');assert.equal(new crypto.X509Certificate(decoded.signerCert).checkPrivateKey(crypto.createPrivateKey(decoded.signerKey)),true);assert.throws(()=>apple.readPfx(encode(pair.privateKey),'wrong'));assert.throws(()=>apple.readPfx(encode(null),'test-password'));});
