import { trialDisplay } from '@/lib/trial-display';
import { requireAdmin } from '@/lib/auth';
import { recentAdminAudit } from '@/lib/security';
import { listBusinesses } from '@/lib/store';
import { Building2, ExternalLink, Plus, ShieldCheck, Store, CreditCard, CircleCheck, CirclePause, Clock3 } from 'lucide-react';
import { listActorSessions } from '@/lib/auth-store';
import SessionSecurityCard from '@/components/SessionSecurityCard';
import DashboardShell from '@/components/DashboardShell';
import { billingStatusLabel } from '@/lib/billing';
import Link from 'next/link';
import { SALON_PUBLIC_ORIGIN } from '@/lib/salon-links';

export default async function AdminPage({searchParams,view='overview'}:{searchParams:Promise<Record<string,string|undefined>>,view?:string}){
 const adminSession=await requireAdmin();
 const [salons,auditRows,sessions]=await Promise.all([listBusinesses(),recentAdminAudit(30),listActorSessions('admin',adminSession.sub)]);
 const q=await searchParams;
 const baseUrl=SALON_PUBLIC_ORIGIN;
 return <DashboardShell role="admin" name={adminSession.name||'Admin'} businessName="Rezix Control Center">
  <section id="overview" className="dashboard-hero"><div><span className="eyebrow">REZIX CONTROL CENTER</span><h1>{{"overview": "Dein Control Center", "new-salon": "Betrieb anlegen", "salons": "Alle Betriebe", "system": "Einstellungen & Sicherheit", "subscriptions":"Abonnements"}[view]}</h1><p>Betriebe, Tarife und Zugänge zentral verwalten.</p></div><div className="role-status"><ShieldCheck size={15}/> System Admin</div></section>
  {view==='overview'&&(<div className="metrics dashboard-metrics"><Metric label="Betriebe gesamt" value={String(salons.length)} icon={<Store/>}/><Metric label="Aktive Betriebe" value={String(salons.filter(s=>s.active).length)} icon={<CircleCheck/>}/><Metric label="Free Trial" value={String(salons.filter(s=>s.subscriptionStatus==='trialing').length)} icon={<Clock3/>}/><Metric label="Bezahlte Tarife" value={String(salons.filter(s=>s.billingPlan!=='trial').length)} icon={<CreditCard/>}/></div>)}
  {q.created&&<div className="success salon-created-success">Salon wurde erfolgreich erstellt.</div>}{q.mailError&&<div className="alert">Salon erstellt, aber die Verifizierungs-E-Mail konnte nicht versendet werden.</div>}{q.error&&<div className="alert">Salon konnte nicht erstellt werden. Prüfe die Eingaben.</div>}{q.upload&&<div className="alert">Bild-Upload fehlgeschlagen. Prüfe Storage und Dateigröße.</div>}
  {q.saved&&<div className="success">Änderungen gespeichert.</div>}{q.updateError&&<div className="alert">{q.updateError==='managed'?'Ein laufendes Abonnement kann nur im Zahlungsportal geändert werden.':'Änderung konnte nicht gespeichert werden. Bitte Eingaben prüfen.'}</div>}{q.reset&&<div className={q.reset==='sent'?'success':'alert'}>{q.reset==='sent'?'Zugangslink wurde versendet.':q.reset==='limited'?'Zu viele Anfragen. Bitte später erneut versuchen.':'E-Mail konnte nicht versendet werden. Bitte E-Mail-Konfiguration prüfen.'}</div>}
  {view==='subscriptions'&&<section className="panel"><div className="panel-head"><div><span className="section-kicker">ABRECHNUNG</span><h2>Abonnements & Testphasen</h2></div><span className="admin-salon-count">{salons.length} Betriebe</span></div>{salons.length===0?<p className="muted">Noch keine Betriebe vorhanden.</p>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Salon</th><th>Tarif</th><th>Status</th><th>Testphase / Laufzeit</th><th>Verwaltung</th></tr></thead><tbody>{salons.map(b=><tr key={b.id}><td><b>{b.name}</b><small>{b.managerEmail}</small></td><td>{planLabel(b.billingPlan)}</td><td>{billingStatusLabel(b.subscriptionStatus)}{b.cancelAtPeriodEnd?' · Kündigung vorgemerkt':''}</td><td>{b.subscriptionStatus==='trialing'?trialDisplay(b.trialEndsAt,b.subscriptionStatus,b.trialStartedAt):b.subscriptionCurrentPeriodEnd?new Date(b.subscriptionCurrentPeriodEnd).toLocaleDateString('de-AT'):'–'}</td><td><Link href={`/admin/salons/${b.id}`}>Öffnen</Link></td></tr>)}</tbody></table></div>}</section>}
  <div className="dashboard-page-section">
   {view==='new-salon'&&(<section id="new-salon" className="panel salon-registration"><div className="section-kicker">NEUER BETRIEB</div><h2><Plus size={20}/> Betrieb registrieren</h2><p className="muted">Logo: PNG, JPG oder WEBP bis 2 MB. Der Stempel wird später als Symbol im Karten-Designer gewählt.</p>
    <form className="stack-form" method="post" action="/api/admin/business/create" encType="multipart/form-data"><label>Betriebsname</label><input name="name" placeholder="z. B. Royal Cuts" required/><label>URL-Kürzel (Slug)</label><input name="slug" placeholder="royal-cuts" pattern="[a-zA-Z0-9äöüÄÖÜß -]+" required/><small className="muted">Öffentliche Karte: {baseUrl}/s/royal-cuts</small><div className="form-split"><div><label>Stempelziel</label><input name="rewardTarget" type="number" min="2" max="30" defaultValue="10" required/></div><div><label>Belohnung</label><input name="rewardText" defaultValue="Ein kostenloser Haarschnitt" required/></div></div><label>Betriebs-Logo</label><input name="logo" type="file" accept="image/png,image/jpeg,image/webp" required/><hr/><h3>Manager-Zugang</h3><label>Name des Managers</label><input name="managerName" required/><label>E-Mail des Managers</label><input name="managerEmail" type="email" required/><label>Temporäres Passwort</label><input name="managerPassword" type="password" minLength={12} required/><button className="gold" type="submit">Betrieb erstellen</button></form>
   </section>)}
   {view==='salons'&&(<section id="salons" className="panel"><div className="panel-head"><div><div className="section-kicker">BETRIEBE</div><h2><Store size={20}/> Registrierte Betriebe</h2><p className="muted">Kundendaten bleiben ausschließlich im Manager-Bereich des jeweiligen Betriebs.</p></div><Link className="secondary" href="/admin/new-salon">Betrieb anlegen</Link><span className="admin-salon-count">{salons.length} Betriebe</span></div>{salons.length===0?<div className="empty-block"><Building2 size={36}/><b>Noch keine Betriebe</b><span>Erstelle deinen ersten Betrieb über „Betrieb anlegen“.</span></div>:<div className="salon-list">{salons.map(s=>{const plan=planLabel(s.billingPlan);const trial=trialDisplay(s.trialEndsAt,s.subscriptionStatus,s.trialStartedAt);return <div className="salon-row admin-salon-row" key={s.id}>{s.logoUrl?<img className="salon-logo" src={s.logoUrl} alt=""/>:<div className="salon-logo placeholder"><Store/></div>}<div className="salon-meta"><div className="salon-title-line"><b>{s.name}</b><span className={`salon-state ${s.active?'is-active':'is-disabled'}`}>{s.archivedAt?'Archiviert':s.active?<><CircleCheck size={12}/> Aktiv</>:<><CirclePause size={12}/> Gesperrt</>}</span></div><span>Manager: {s.managerEmail||'Kein Manager zugeordnet'}</span><small>{s.rewardTarget} Stempel · {s.rewardText}</small><div className="salon-badges"><span className={`plan-badge plan-${s.billingPlan}`}><CreditCard size={12}/>{plan}</span><span className={`subscription-badge sub-${s.subscriptionStatus}`}>{billingStatusLabel(s.subscriptionStatus)}</span>{trial&&<span className="trial-remaining"><Clock3 size={12}/>{trial}</span>}</div><div className="salon-access-links"><div><span>Kundenkarte</span><a href={`${baseUrl}/s/${encodeURIComponent(s.slug)}`} target="_blank" rel="noopener noreferrer"><span>{baseUrl}/s/{s.slug}</span><ExternalLink size={14} aria-hidden="true"/></a></div><div><span>Manager-Anmeldung</span><a href={`${baseUrl}/manager/login`} target="_blank" rel="noopener noreferrer"><span>{baseUrl}/manager/login</span><ExternalLink size={14} aria-hidden="true"/></a></div></div><Link className="secondary link-button" href={`/admin/salons/${s.id}`} style={{marginTop:14}}>Betrieb verwalten</Link></div></div>})}</div>}</section>)}
  </div>
  {view==='system'&&(<section id="system" className="dashboard-section"><div className="section-heading"><div><span className="section-kicker">SYSTEM</span><h2>Sicherheit & Sitzungen</h2></div></div><SessionSecurityCard sessions={sessions} currentJti={adminSession.jti} revoked={!!q.sessionsRevoked}/><div className="panel quick" style={{marginTop:16}}><h2>Admin Audit</h2>{auditRows.length===0?<div className="empty-block"><ShieldCheck size={30}/><b>Noch keine Ereignisse</b></div>:<div className="attention">{auditRows.slice(0,12).map((a:any,i:number)=><div className="row" key={`${a.created_at}-${i}`}><div className="avatar sm"><ShieldCheck size={15}/></div><div><b>{auditLabel(String(a.action))}</b><span>{new Date(a.created_at).toLocaleString('de-DE')}</span></div></div>)}</div>}</div></section>)}
 {view==='overview'&&<div className="workspace-grid"><Link className="workspace-card" href="/admin/new-salon"><span className="section-kicker">VERWALTUNG</span><h2>Betrieb anlegen</h2><p>Einen neuen Salon und Manager einrichten.</p><span className="workspace-card-action">Bereich öffnen →</span></Link><Link className="workspace-card" href="/admin/salons"><span className="section-kicker">VERWALTUNG</span><h2>Alle Betriebe</h2><p>Tarife und Status aller Betriebe prüfen.</p><span className="workspace-card-action">Bereich öffnen →</span></Link><Link className="workspace-card" href="/admin/system"><span className="section-kicker">VERWALTUNG</span><h2>Sicherheit & System</h2><p>Sitzungen und Sicherheitsereignisse prüfen.</p><span className="workspace-card-action">Bereich öffnen →</span></Link></div>}</DashboardShell>;
}
function Metric({label,value,icon}:{label:string,value:string,icon:React.ReactNode}){return <div className="metric"><div className="iconbox">{icon}</div><span>{label}</span><b>{value}</b><small>Live</small></div>}
function auditLabel(a:string){const m:Record<string,string>={'auth.login.success':'Anmeldung erfolgreich','auth.login.failed':'Anmeldung fehlgeschlagen','auth.logout':'Abmeldung','friseur.created':'Friseur-Zugang erstellt','stamp.added':'Stempel hinzugefügt','stamp.failed.not_found':'Ungültiger Kundencode','kunde.registered':'Kunde registriert','business.created':'Salon erstellt','billing.checkout.created':'Zahlung gestartet','billing.checkout.failed':'Zahlung fehlgeschlagen','billing.portal.opened':'Zahlungsportal geöffnet'};return m[a]||a}

function planLabel(plan:string){const m:Record<string,string>={trial:'Free Trial',starter:'Starter',professional:'Professional',business:'Business'};return m[plan]||plan}
