 'use client';
import { useEffect,useState,useRef } from 'react';
import { designAppearance,type CustomerDesign } from '@/lib/customer-design';
export default function CustomerDesignFields({design,onChange}:{design:CustomerDesign;onChange:(d:CustomerDesign)=>void}){
 const appearance=designAppearance(design);
 const originalImage=useRef(design.imageUrl);const [removed,setRemoved]=useState(false);
 const [file,setFile]=useState<File|null>(null);
 useEffect(()=>{const url=file?URL.createObjectURL(file):null;onChange({...design,imageUrl:removed?null:url||originalImage.current,...(file&&!removed?{mode:'image' as const}:{})});return()=>{if(url)URL.revokeObjectURL(url);};},[file,removed]);
 const update=(patch:Partial<CustomerDesign>)=>onChange({...design,...patch});
 return <fieldset className="customer-design-fields"><legend>Kunden-Seite Design</legend><p className="muted">Gestalte nur deine digitale Kundenkarte: Hintergrund, Textfarben und Schrift. Die Webseite behält ihr eigenes Design. PNG, JPG oder WEBP bis 2 MB.</p>
 <label htmlFor="background-mode">Hintergrund</label><select id="background-mode" name="backgroundMode" value={design.mode} onChange={e=>update({mode:e.target.value as CustomerDesign['mode']})}><option value="color">Einfarbig</option><option value="gradient">Farbverlauf</option><option value="image">Bild</option></select>
 <div className="form-split"><div><label htmlFor="background-color">Hintergrundfarbe</label><input id="background-color" name="backgroundColor" type="color" value={design.color} onChange={e=>update({color:e.target.value})}/></div><div><label htmlFor="gradient-color">Verlaufsfarbe</label><input id="gradient-color" name="gradientColor" type="color" value={design.gradientColor} onChange={e=>update({gradientColor:e.target.value})}/></div></div>
 <label htmlFor="background-file">Hintergrundbild</label><input id="background-file" name="background" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>2097152){e.target.setCustomValidity('Bitte ein Bild bis 2 MB wählen.');e.target.reportValidity();return;}e.target.setCustomValidity('');setFile(f||null);}}/>
 <label className="checkline"><input type="checkbox" name="removeBackground" checked={removed} onChange={e=>setRemoved(e.target.checked)}/> Gespeichertes Hintergrundbild entfernen</label>
 <label htmlFor="background-overlay">Weiße Überlagerung · {Math.round(design.overlay*100)} %</label><input id="background-overlay" name="backgroundOverlay" type="range" min="0" max="1" step="0.05" value={design.overlay} onChange={e=>update({overlay:Number(e.target.value)})}/>
 <div className="form-split"><div><label htmlFor="background-position">Bildposition</label><select id="background-position" name="backgroundPosition" value={design.position} onChange={e=>update({position:e.target.value as CustomerDesign['position']})}><option value="center">Mitte</option><option value="top">Oben</option><option value="bottom">Unten</option></select></div><div><label htmlFor="background-size">Bildgröße</label><select id="background-size" name="backgroundSize" value={design.size} onChange={e=>update({size:e.target.value as CustomerDesign['size']})}><option value="cover">Ausfüllen (cover)</option><option value="contain">Vollständig (contain)</option></select></div></div><h3>Transparenz & Text</h3><p className="muted">0 % lässt dein Hintergrundbild vollständig durchscheinen. Farben und Schrift werden direkt in der Vorschau angezeigt.</p>
 <label htmlFor="panel-opacity">Deckkraft der Kartenfläche · {Math.round(appearance.panelOpacity*100)} %</label><input id="panel-opacity" name="panelOpacity" type="range" min="0" max="1" step="0.05" value={appearance.panelOpacity} onChange={e=>update({panelOpacity:Number(e.target.value)})}/>
 {([{key:'headingColor',label:'Überschriftenfarbe'},{key:'textColor',label:'Textfarbe'},{key:'mutedColor',label:'Untertitel & Hinweise'}] as const).map(({key,label})=><div key={key}><label htmlFor={key}>{label}</label><input id={key} name={key} type="color" value={appearance[key]} onChange={e=>update({[key]:e.target.value})}/></div>)}
 <label htmlFor="fontFamily">Schriftart</label><select id="fontFamily" name="fontFamily" value={appearance.fontFamily} onChange={e=>update({fontFamily:e.target.value as CustomerDesign['fontFamily']})}><option value="sans">Modern</option><option value="serif">Elegant</option><option value="rounded">Weich</option></select>
 <div className="form-split"><div><label htmlFor="fontStyle">Schriftstil</label><select id="fontStyle" name="fontStyle" value={appearance.fontStyle} onChange={e=>update({fontStyle:e.target.value as CustomerDesign['fontStyle']})}><option value="normal">Normal</option><option value="italic">Kursiv</option></select></div><div><label htmlFor="fontWeight">Schriftstärke</label><select id="fontWeight" name="fontWeight" value={appearance.fontWeight} onChange={e=>update({fontWeight:e.target.value as CustomerDesign['fontWeight']})}><option value="400">Normal</option><option value="600">Halbfett</option><option value="700">Fett</option></select></div></div>
 <label htmlFor="fontSize">Textgröße · {appearance.fontSize} px</label><input id="fontSize" name="fontSize" type="range" min="12" max="22" step="1" value={appearance.fontSize} onChange={e=>update({fontSize:Number(e.target.value)})}/>
 <label htmlFor="headingSize">Überschriftengröße · {appearance.headingSize} px</label><input id="headingSize" name="headingSize" type="range" min="18" max="42" step="1" value={appearance.headingSize} onChange={e=>update({headingSize:Number(e.target.value)})}/>
 </fieldset>;
}
