'use client';
import { useEffect,useState } from 'react'; import { QRCodeSVG } from 'qrcode.react'; import { Scissors,Gift,History,CheckCircle2 } from 'lucide-react';
type Data={customer:{name:string;code:string;stamps:number;rewardsRedeemed:number;lastVisitAt:string|null};business:{name:string;rewardTarget:number;rewardText:string}};
export default function CustomerApp(){ const [token,setToken]=useState<string|null>(null); const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{ const t=localStorage.getItem('rezix_customer_token'); setToken(t); if(!t){setLoading(false);return;} fetch('/api/customer/me?token='+encodeURIComponent(t)).then(async r=>{if(!r.ok) throw new Error(); return r.json()}).then(setData).catch(()=>{localStorage.removeItem('rezix_customer_token');setToken(null)}).finally(()=>setLoading(false));},[]);
 async function register(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); setError(''); const fd=new FormData(e.currentTarget); const r=await fetch('/api/customer/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:fd.get('name'),phone:fd.get('phone')})}); const j=await r.json(); if(!r.ok){setError(j.error||'Registrierung fehlgeschlagen');return;} localStorage.setItem('rezix_customer_token',j.token); location.reload();}
 if(loading) return <main><section className="join"><div className="join-card"><h1>Rezix Loyalty</h1><p>Wird geladen…</p></div></section></main>;
 if(!token||!data) return <main><header className="topbar"><div className="brand"><img src="/icon.svg" alt="Rezix"/><div><b>REZIX</b><span>LOYALTY</span></div></div></header><section className="join"><form className="join-card" onSubmit={register}><img src="/icon.svg" alt="Rezix"/><span className="eyebrow">DIGITALE TREUEKARTE</span><h1>Deine Karte. Ohne App.</h1><p>Registriere dich einmal. Danach bleibt deine Rezix-Karte auf diesem Gerät verfügbar.</p>{error&&<div className="alert">{error}</div>}<label>Name</label><input name="name" autoComplete="name" required/><label>Telefonnummer</label><input name="phone" type="tel" autoComplete="tel" required/><button className="gold full" type="submit">Treuekarte erstellen</button><small>Es gibt keinen Zugriff auf Mitarbeiter- oder Verwaltungsbereiche über diese Oberfläche.</small></form></section></main>;
 const {customer,business}=data; const remaining=Math.max(0,business.rewardTarget-customer.stamps); return <main><header className="topbar customer-topbar"><div className="brand"><img src="/icon.svg" alt="Rezix"/><div><b>REZIX</b><span>LOYALTY</span></div></div><div className="customer-badge"><CheckCircle2 size={15}/> Mitgliedskarte</div></header><div className="shell customer-layout"><section className="hero"><div><span className="eyebrow">{business.name.toUpperCase()}</span><h1>Hallo, {customer.name}.</h1><p>Deine digitale Treuekarte – sicher auf diesem Gerät gespeichert.</p></div><div className="mini-stat"><b>{customer.stamps}/{business.rewardTarget}</b><span>Stempel gesammelt</span></div></section><section className="loyalty-card"><div className="card-head"><div><small>Deine Treuekarte</small><h2>{business.name}</h2></div><span className="status">Aktiv</span></div><div className="stamps">{Array.from({length:business.rewardTarget}).map((_,i)=><div className={i<customer.stamps?'stamp active':'stamp'} key={i}>{i<customer.stamps?<Scissors size={19}/>:i+1}</div>)}</div><div className="progress"><div style={{width:`${Math.min(100,(customer.stamps/business.rewardTarget)*100)}%`}}/></div><p className="reward-copy">{remaining>0?<>Noch <b>{remaining}</b> {remaining===1?'Stempel':'Stempel'} bis zu: <b>{business.rewardText}</b>.</>:<>🎉 Deine Belohnung ist bereit: <b>{business.rewardText}</b></>}</p><div className="qr-panel"><QRCodeSVG value={customer.code} size={138} bgColor="#fff" fgColor="#0b0b0b"/><div><b>Zeige diesen Code deinem Barber</b><span>Kundencode {customer.code}</span><small>Nur angemeldete Mitarbeiter können Stempel hinzufügen.</small></div></div></section><section className="grid3"><Info icon={<Gift/>} title="Belohnung" text={business.rewardText}/><Info icon={<History/>} title="Letzter Besuch" text={customer.lastVisitAt?new Date(customer.lastVisitAt).toLocaleDateString('de-DE'):'Noch kein Besuch erfasst'}/><Info icon={<CheckCircle2/>} title="Eingelöste Belohnungen" text={String(customer.rewardsRedeemed)}/></section></div></main> }
function Info({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="info"><div className="iconbox">{icon}</div><div><b>{title}</b><span>{text}</span></div></div>}
