'use client';
import { useEffect,useRef,useState } from 'react';
import { ImageOff, Move } from 'lucide-react';
import { designAppearance,type CustomerDesign } from '@/lib/customer-design';
export default function CustomerDesignFields({design,onChange}:{design:CustomerDesign;onChange:(d:CustomerDesign)=>void}){
 const appearance=designAppearance(design),originalImage=useRef(design.imageUrl),[removed,setRemoved]=useState(false),[file,setFile]=useState<File|null>(null);
 useEffect(()=>{const url=file?URL.createObjectURL(file):null;onChange({...design,imageUrl:removed?null:url||originalImage.current,...(file&&!removed?{mode:'image' as const}:{})});return()=>{if(url)URL.revokeObjectURL(url);};},[file,removed]);
 const update=(patch:Partial<CustomerDesign>)=>onChange({...design,...patch});
 return <fieldset className="customer-design-fields"><legend>Hintergrund & Typografie</legend><p className="muted">Wähle einen Hintergrundtyp. Es werden nur die Einstellungen angezeigt, die dafür wirklich relevant sind.</p>
 <div className="design-mode-tabs">{([['color','Einfarbig'],['gradient','Farbverlauf'],['image','Bild']] as const).map(([v,l])=><button type="button" key={v} className={design.mode===v?'active':''} onClick={()=>update({mode:v})}>{l}</button>)}</div><input type="hidden" name="backgroundMode" value={design.mode}/>
 {design.mode==='color'&&<div className="design-context"><label>Hintergrundfarbe</label><input name="backgroundColor" type="color" value={design.color} onChange={e=>update({color:e.target.value})}/><input type="hidden" name="gradientColor" value={design.gradientColor}/></div>}
 {design.mode==='gradient'&&<div className="design-context"><div className="form-split"><div><label>Startfarbe</label><input name="backgroundColor" type="color" value={design.color} onChange={e=>update({color:e.target.value})}/></div><div><label>Endfarbe</label><input name="gradientColor" type="color" value={design.gradientColor} onChange={e=>update({gradientColor:e.target.value})}/></div></div></div>}
 {design.mode==='image'&&<div className="design-context image-controls"><input type="hidden" name="backgroundColor" value={design.color}/><input type="hidden" name="gradientColor" value={design.gradientColor}/><label>Hintergrundbild</label><input name="background" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>2097152){e.target.setCustomValidity('Bitte ein Bild bis 2 MB wählen.');e.target.reportValidity();return;}e.target.setCustomValidity('');setRemoved(false);setFile(f||null);}}/>{(design.imageUrl||originalImage.current)&&<button className="remove-image-button" type="button" onClick={()=>{setRemoved(true);setFile(null)}}><ImageOff size={16}/> Bild entfernen</button>}<input type="hidden" name="removeBackground" value={removed?'on':''}/><div className="image-move-title"><Move size={16}/> Bild frei positionieren</div><label>Horizontal · {design.positionX??50}%</label><input name="backgroundPositionX" type="range" min="0" max="100" value={design.positionX??50} onChange={e=>update({positionX:Number(e.target.value)})}/><label>Vertikal · {design.positionY??50}%</label><input name="backgroundPositionY" type="range" min="0" max="100" value={design.positionY??50} onChange={e=>update({positionY:Number(e.target.value)})}/><input type="hidden" name="backgroundPosition" value="center"/><label>Bildgröße</label><select name="backgroundSize" value={design.size} onChange={e=>update({size:e.target.value as CustomerDesign['size']})}><option value="cover">Fläche ausfüllen</option><option value="contain">Bild vollständig zeigen</option></select><label>Helle Überlagerung · {Math.round(design.overlay*100)}%</label><input name="backgroundOverlay" type="range" min="0" max="1" step="0.05" value={design.overlay} onChange={e=>update({overlay:Number(e.target.value)})}/></div>}
 {design.mode!=='image'&&<><input type="hidden" name="backgroundOverlay" value={design.overlay}/><input type="hidden" name="backgroundPosition" value="center"/><input type="hidden" name="backgroundPositionX" value={design.positionX??50}/><input type="hidden" name="backgroundPositionY" value={design.positionY??50}/><input type="hidden" name="backgroundSize" value={design.size}/></>}
 <h3>Text</h3><label>Deckkraft der Kartenfläche · {Math.round(appearance.panelOpacity*100)}%</label><input name="panelOpacity" type="range" min="0" max="1" step="0.05" value={appearance.panelOpacity} onChange={e=>update({panelOpacity:Number(e.target.value)})}/><div className="form-split">{([{key:'headingColor',label:'Überschrift'},{key:'textColor',label:'Text'}] as const).map(({key,label})=><div key={key}><label>{label}</label><input name={key} type="color" value={appearance[key]} onChange={e=>update({[key]:e.target.value})}/></div>)}</div><label>Hinweisfarbe</label><input name="mutedColor" type="color" value={appearance.mutedColor} onChange={e=>update({mutedColor:e.target.value})}/><label>Schriftart</label><select name="fontFamily" value={appearance.fontFamily} onChange={e=>update({fontFamily:e.target.value as CustomerDesign['fontFamily']})}><option value="sans">Modern</option><option value="serif">Elegant</option><option value="rounded">Weich</option></select><div className="form-split"><div><label>Stil</label><select name="fontStyle" value={appearance.fontStyle} onChange={e=>update({fontStyle:e.target.value as CustomerDesign['fontStyle']})}><option value="normal">Normal</option><option value="italic">Kursiv</option></select></div><div><label>Stärke</label><select name="fontWeight" value={appearance.fontWeight} onChange={e=>update({fontWeight:e.target.value as CustomerDesign['fontWeight']})}><option value="400">Normal</option><option value="600">Halbfett</option><option value="700">Fett</option></select></div></div><input type="hidden" name="fontSize" value={appearance.fontSize}/><input type="hidden" name="headingSize" value={appearance.headingSize}/></fieldset>;
}
