'use client';
import { useEffect,useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { Scissors,Gift,History,CheckCircle2 } from 'lucide-react';

type Data={customer:{name:string;code:string;stamps:number;rewardsRedeemed:number;lastVisitAt:string|null};business:{id:string;slug:string;name:string;rewardTarget:number;rewardText:string;logoUrl:string|null;stampUrl:string|null;cardTitle:string;cardSubtitle:string;primaryColor:string;stampShape:'circle'|'rounded'|'square'}};
export default function CustomerApp({slug,salon}:{slug:string;salon:{name:string;logoUrl:string|null}}){
 const [token,setToken]=useState<string|null>(null);const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [challengeId,setChallengeId]=useState<string|null>(null);const [devOtp,setDevOtp]=useState<string|null>(null);const storageKey=`rezix_customer_token_${slug}`;
 useEffect(()=>{const t=localStorage.getItem(storageKey);setToken(t);if(!t){setLoading(false);return;}fetch('/api/customer/me?token='+encodeURIComponent(t),{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then((j:Data)=>{if(j.business.slug!==slug)throw new Error();setData(j)}).catch(()=>{localStorage.removeItem(storageKey);setToken(null)}).finally(()=>setLoading(false));},[slug]);
 async function register(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const fd=new FormData(e.currentTarget);const r=await fetch('/api/customer/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug,name:fd.get('name'),email:fd.get('email'),privacyAcknowledged:fd.get('termsAccepted')==='on',marketingConsent:false})});const j=await r.json();if(!r.ok){setError(j.error||'Registrierung fehlgeschlagen');return;}setChallengeId(j.challengeId);setDevOtp(j.devOtp||null);}
 async function verifyOtp(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!challengeId)return;setError('');const fd=new FormData(e.currentTarget);const r=await fetch('/api/customer/verify-otp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({challengeId,code:fd.get('code')})});const j=await r.json();if(!r.ok){setError(j.error||'Code konnte nicht bestätigt werden');return;}localStorage.setItem(storageKey,j.token);location.reload();}
 if(loading)return <main><section className="join"><div className="join-card"><h1>Rezix Loyalty</h1><p>Wird geladen…</p></div></section></main>;
 if(!token||!data)return <main><header className="topbar"><Brand name={salon.name} logo={salon.logoUrl}/></header><section className="join">{!challengeId?<form className="join-card" onSubmit={register}>{salon.logoUrl?<img src={salon.logoUrl} alt={salon.name}/>:<img src="/rezix-logo.svg" alt="Rezix"/>}<span className="eyebrow">DIGITALE TREUEKARTE</span><h1>{salon.name}</h1><p>Einmal registrieren, E-Mail bestätigen und deine digitale Treuekarte nutzen.</p>{error&&<div className="alert">{error}</div>}<label>Name</label><input name="name" autoComplete="name" required/><label>E-Mail-Adresse</label><input name="email" type="email" autoComplete="email" placeholder="name@example.at" required/><small>Du erhältst einen 6-stelligen Bestätigungscode per E-Mail.</small><label className="checkline"><input name="termsAccepted" type="checkbox" required/><span>Ich akzeptiere die <a href="/agb" target="_blank">AGB</a> und habe die <a href="/datenschutz" target="_blank">Datenschutzerklärung</a> gelesen.</span></label><button className="gold full" type="submit">Code per E-Mail senden</button></form>:<form className="join-card" onSubmit={verifyOtp}><img src="/rezix-logo.svg" alt="Rezix"/><span className="eyebrow">E-MAIL BESTÄTIGEN</span><h1>Sicherheitscode</h1><p>Gib den 6-stelligen Code aus deiner E-Mail ein. Er ist 10 Minuten gültig.</p>{devOtp&&<div className="success">Lokaler Test-Code: <b>{devOtp}</b></div>}{error&&<div className="alert">{error}</div>}<label>6-stelliger Code</label><input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" required autoFocus/><button className="gold full" type="submit">Code bestätigen</button><button className="secondary full" type="button" onClick={()=>{setChallengeId(null);setDevOtp(null);setError('')}}>Zurück</button></form>}</section></main>;
 const {customer,business}=data;const remaining=Math.max(0,business.rewardTarget-customer.stamps);const accent=business.primaryColor||'#2563EB';
 return <main style={{'--salon-accent':accent} as React.CSSProperties}><header className="topbar customer-topbar"><Brand name={business.name} logo={business.logoUrl}/><div className="customer-badge"><CheckCircle2 size={15}/> Mitgliedskarte</div></header><div className="shell customer-layout"><section className="hero"><div><span className="eyebrow">{business.name.toUpperCase()}</span><h1>Hallo, {customer.name}.</h1><p>{business.cardSubtitle}</p></div><div className="mini-stat"><b style={{color:accent}}>{customer.stamps}/{business.rewardTarget}</b><span>Stempel gesammelt</span></div></section><section className="loyalty-card"><div className="card-head"><div><small>{business.cardTitle}</small><h2>{business.name}</h2></div><span className="status">Aktiv</span></div><div className={`stamps shape-${business.stampShape}`}>{Array.from({length:business.rewardTarget}).map((_,i)=><div className={i<customer.stamps?'stamp active':'stamp'} style={i<customer.stamps?{backgroundColor:accent,borderColor:accent}:undefined} key={i}>{i<customer.stamps?(business.stampUrl?<img className="stamp-image" src={business.stampUrl} alt="Stempel"/>:<Scissors size={19}/>):i+1}</div>)}</div><div className="progress"><div style={{width:`${Math.min(100,(customer.stamps/business.rewardTarget)*100)}%`,backgroundColor:accent}}/></div><p className="reward-copy">{remaining>0?<>Noch <b>{remaining}</b> Stempel bis zu: <b>{business.rewardText}</b>.</>:<>🎉 Deine Belohnung ist bereit: <b>{business.rewardText}</b></>}</p><div className="qr-panel"><QRCodeSVG value={customer.code} size={138} bgColor="#fff" fgColor="#0b1739"/><div><b>Zeige diesen Code deinem Friseur</b><span>Kundencode {customer.code}</span><small>Nur angemeldete Friseure dieses Salons können Stempel hinzufügen.</small></div></div></section><section className="grid3"><Info icon={<Gift/>} title="Belohnung" text={business.rewardText}/><Info icon={<History/>} title="Letzter Besuch" text={customer.lastVisitAt?new Date(customer.lastVisitAt).toLocaleDateString('de-DE'):'Noch kein Besuch erfasst'}/><Info icon={<CheckCircle2/>} title="Eingelöste Belohnungen" text={String(customer.rewardsRedeemed)}/></section><div className="customer-legal-note">Mit der Nutzung gelten die <a href="/agb">AGB</a> und die <a href="/datenschutz">Datenschutzerklärung</a>.</div></div></main>;
}
function Brand({name,logo}:{name:string;logo:string|null}){return <div className="brand">{logo?<img src={logo} alt={name}/>:<img src="/rezix-logo.svg" alt="Rezix"/>}<div><b>{name.toUpperCase()}</b><span>REZIX LOYALTY</span></div></div>}
function Info({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="info"><div className="iconbox">{icon}</div><div><b>{title}</b><span>{text}</span></div></div>}
