 'use client';
import { useEffect,useRef,useState } from 'react';
import { Play,X,Film } from 'lucide-react';
export default function ExplainerVideo(){
 const dialog=useRef<HTMLDialogElement>(null);const trigger=useRef<HTMLButtonElement>(null);const [open,setOpen]=useState(false);const [failed,setFailed]=useState(false);
 const source=process.env.NEXT_PUBLIC_REZIX_EXPLAINER_VIDEO||'/media/rezix-explainer.mp4';
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.showModal();return()=>{document.body.style.overflow=previous;dialog.current?.close();trigger.current?.focus();};},[open]);
 return <><button ref={trigger} type="button" className="gold explainer-trigger" onClick={()=>{setFailed(false);setOpen(true);}}><Play size={20} fill="currentColor"/> So funktioniert Rezix</button>{open&&<dialog ref={dialog} className="explainer-dialog" aria-labelledby="explainer-title" onCancel={e=>{e.preventDefault();setOpen(false);}} onClick={e=>{if(e.target===e.currentTarget)setOpen(false);}}><div className="explainer-content"><div className="explainer-heading"><div><span className="eyebrow">REZIX LOYALTY</span><h2 id="explainer-title">So funktioniert Rezix</h2></div><button type="button" className="video-close" aria-label="Video schließen" onClick={()=>setOpen(false)} autoFocus><X/></button></div>{failed?<div className="video-placeholder" role="status"><Film size={44}/><h3>Dein Überblick. In Kürze als Video.</h3><p>Digitale Treuekarte öffnen, persönlichen QR-Code zeigen und beim Friseur Stempel sammeln. Ist die Karte voll, bestätigt dein Friseur die Einlösung deiner Belohnung.</p><p>Im Manager-Bereich verwaltest du Kunden, Friseure, Belohnungen und das Design deines Salons.</p></div>:<video controls playsInline preload="metadata" onError={()=>setFailed(true)} src={source} aria-label="Rezix Loyalty Erklärvideo"/>}<p className="video-caption">Mehr Kunden. Mehr Loyalität. Weniger Papier.</p></div></dialog>}</>;
}
