'use client';
import React,{ useEffect,useRef,useState } from 'react';
import { Camera,CameraOff,Keyboard,Plus,ScanLine,CheckCircle2,AlertCircle } from 'lucide-react';

export default function FriseurConsole(){
 const [code,setCode]=useState('');const [customer,setCustomer]=useState<{name:string;code:string;stamps:number}|null>(null);const [target,setTarget]=useState(0);const [msg,setMsg]=useState('');const [error,setError]=useState('');const [cameraOn,setCameraOn]=useState(false);const [cameraBusy,setCameraBusy]=useState(false);const videoRef=useRef<HTMLVideoElement|null>(null);const streamRef=useRef<MediaStream|null>(null);const rafRef=useRef<number|null>(null);const lastScanRef=useRef(0);
 function stopCamera(){if(rafRef.current)cancelAnimationFrame(rafRef.current);rafRef.current=null;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setCameraOn(false)}
 useEffect(()=>()=>stopCamera(),[]);
 async function scanLoop(detector:any){if(!videoRef.current||!streamRef.current)return;const now=Date.now();if(now-lastScanRef.current>300){lastScanRef.current=now;try{const found=await detector.detect(videoRef.current);for(const item of found||[]){const text=String(item.rawValue||'').trim().toUpperCase();const match=text.match(/RZX-[A-F0-9]{8}/);if(match){setCode(match[0]);setMsg('QR-Code erkannt. Du kannst jetzt den Stempel hinzufügen.');stopCamera();return;}}}catch{}}rafRef.current=requestAnimationFrame(()=>scanLoop(detector));}
 async function startCamera(){setError('');setMsg('');if(cameraOn){stopCamera();return;}if(!navigator.mediaDevices?.getUserMedia){setError('Dieser Browser unterstützt keinen Kamerazugriff. Bitte den Kundencode manuell eingeben.');return;}setCameraBusy(true);try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}setCameraOn(true);const Detector=(window as any).BarcodeDetector;if(Detector){const detector=new Detector({formats:['qr_code']});rafRef.current=requestAnimationFrame(()=>scanLoop(detector));}else{setError('Die Kamera ist geöffnet, aber dieser Browser unterstützt die automatische QR-Erkennung nicht. Du kannst den Kundencode weiterhin manuell eingeben.');}}catch(e:any){const name=e?.name||'';if(name==='NotAllowedError'||name==='PermissionDeniedError')setError('Kamerazugriff wurde abgelehnt. Erlaube die Kamera in den Browser-Einstellungen und versuche es erneut.');else setError('Kamera konnte nicht geöffnet werden. Nutze alternativ die manuelle Eingabe.');stopCamera();}finally{setCameraBusy(false)}}
 async function add(){setMsg('');setError('');const r=await fetch('/api/stamp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code})});const j=await r.json();if(!r.ok){setError(j.error||'Fehler');return;}setCustomer(j.customer);setTarget(j.target);setMsg('Stempel wurde erfolgreich hinzugefügt.');}
 return <div className="barber-grid"><section className="scanner"><ScanLine size={50}/><h2>Kunden erfassen</h2><p>QR-Code mit der Kamera scannen oder den Kundencode manuell eingeben.</p><div className="scan-tabs"><button type="button" className={cameraOn?'gold':'secondary'} onClick={startCamera} disabled={cameraBusy}>{cameraOn?<CameraOff size={17}/>:<Camera size={17}/>} {cameraBusy?'Kamera wird geöffnet…':cameraOn?'Kamera schließen':'Kamera öffnen'}</button><span><Keyboard size={16}/> Manuelle Eingabe</span></div><div className={`camera-box ${cameraOn?'active':''}`}><video ref={videoRef} muted playsInline/><div className="camera-frame"><span/><span/><span/><span/></div>{!cameraOn&&<div className="camera-placeholder"><Camera size={38}/><b>Kamera öffnen</b><small>Beim ersten Mal fragt dein Browser nach der Kameraberechtigung.</small></div>}</div><input className="code-input" value={code} onChange={(e:React.ChangeEvent<HTMLInputElement>)=>setCode(e.target.value.toUpperCase())} placeholder="RZX-XXXXXXXX"/><button className="gold" onClick={add} disabled={!code.trim()}><Plus size={18}/> Stempel hinzufügen</button>{msg&&<div className="inline-msg success-inline"><CheckCircle2 size={16}/>{msg}</div>}{error&&<div className="inline-msg error-inline"><AlertCircle size={16}/>{error}</div>}</section><section className="customer-result empty-state">{customer?<><div className="avatar">{customer.name.slice(0,2).toUpperCase()}</div><div className="person"><h2>{customer.name}</h2><p>{customer.code}</p></div><div className="score">{customer.stamps}/{target}</div><p>Der Besuch wurde protokolliert.</p></>:<><h2>Kein Kunde ausgewählt</h2><p>Nach dem Scan eines gültigen Kundencodes erscheinen hier die Daten dieses Kunden.</p></>}</section></div>
}
