'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import ExplainerVideo from './ExplainerVideo';
import LanguageSwitcher from './LanguageSwitcher';
import {ArrowUpRight,Check,Gift,QrCode,Palette,Users,Scissors,ShieldCheck,Home,Grid2X2,Tag,Mail} from 'lucide-react';
type Lang='de'|'en'|'ar';
const copy={
 de:{label:'FÜR BETRIEBE, DIE IN ERINNERUNG BLEIBEN',h1:<>Aus einem Besuch<br/>wird ein<br/><em>Wiedersehen.</em></>,intro:'Deine digitale Treuekarte. Dein Marken-Design. Ein einfacher QR-Scan verbindet dein Team mit Kunden, die gerne wiederkommen.',register:'Registrieren',login:'Login',trial:'3 Tage kostenlos testen',payment:'Keine Zahlungsdaten',note:'Schon Kunde eines Salons? Deine persönliche Karte öffnest du über dessen Link oder QR-Code.',card:'Schön, dass du wieder da bist.',cardp:'Jeder Besuch bringt dich deiner Belohnung näher.',reward:'Vorfreude inklusive.',steps:'Drei Schritte. Viele Gründe wiederzukommen.',stepsp:'Weniger Papier im Portemonnaie. Mehr Verbindung zu deinem Salon.',s1:'Treue immer dabei.',s2:'Ein Scan. Ein Stempel.',s3:'Volle Karte. Gute Laune.',management:'Alles, was Treue persönlich macht.',cta:'3 Tage ausprobieren. Deinen Salon neu verbinden.'},
 en:{label:'FOR BUSINESSES CUSTOMERS REMEMBER',h1:<>One visit<br/>becomes a<br/><em>return visit.</em></>,intro:'Your digital loyalty card. Your brand design. One simple QR scan connects your team with customers who love to return.',register:'Get started',login:'Login',trial:'Try free for 3 days',payment:'No payment details',note:'Already a customer? Open your personal card using your business link or QR code.',card:'Great to see you again.',cardp:'Every visit brings you closer to your reward.',reward:'Something to look forward to.',steps:'Three steps. Many reasons to return.',stepsp:'Less paper in your wallet. A stronger connection to your business.',s1:'Loyalty always with you.',s2:'One scan. One stamp.',s3:'Full card. Happy customer.',management:'Everything that makes loyalty personal.',cta:'Try it for 3 days. Reconnect with your customers.'},
 ar:{label:'للأعمال التي تبقى في الذاكرة',h1:<>من زيارة واحدة<br/>إلى<br/><em>موعد جديد.</em></>,intro:'بطاقة ولاء رقمية بتصميم علامتك. مسح QR بسيط يربط فريقك بالعملاء الذين يحبون العودة.',register:'ابدأ الآن',login:'تسجيل الدخول',trial:'تجربة مجانية 3 أيام',payment:'بدون بيانات دفع',note:'هل أنت عميل بالفعل؟ افتح بطاقتك الشخصية من رابط المتجر أو رمز QR.',card:'سعداء بعودتك.',cardp:'كل زيارة تقرّبك أكثر من مكافأتك.',reward:'مكافأتك تقترب.',steps:'ثلاث خطوات. أسباب كثيرة للعودة.',stepsp:'بطاقات ورقية أقل، وعلاقة أقوى مع عملائك.',s1:'بطاقتك معك دائماً.',s2:'مسح واحد. ختم واحد.',s3:'بطاقة مكتملة. عميل سعيد.',management:'كل ما يجعل الولاء شخصياً.',cta:'جرّب Rezix لمدة 3 أيام.'}
} as const;
export default function HomeContent(){const [lang,setLang]=useState<Lang>('de');useEffect(()=>{const read=()=>setLang((localStorage.getItem('rezix_language')||'de') as Lang);read();const fn=(e:Event)=>setLang((e as CustomEvent<Lang>).detail);window.addEventListener('rezix-language',fn);return()=>window.removeEventListener('rezix-language',fn)},[]);const t=copy[lang];return <main className="marketing-page marketing-v2">
<header className="topbar"><Link className="brand" href="/" aria-label="Rezix"><img src="/rezix-loyalty-new.png" alt="Rezix"/></Link><nav className="marketing-nav"><a className="nav-pill active" href="#home"><Home size={18}/> Home</a><a className="nav-pill" href="#funktionen"><Grid2X2 size={18}/> Funktionen</a><a className="nav-pill" href="#preise"><Tag size={18}/> Preise</a><a className="nav-pill" href="#ueber-uns"><Users size={18}/> Über uns</a><a className="nav-pill" href="#kontakt"><Mail size={18}/> Kontakt</a></nav><div className="topbar-actions"><LanguageSwitcher/><Link className="secondary" href="/manager/login">{t.login}</Link><Link className="gold" href="/manager/register">{t.register} <ArrowUpRight size={18}/></Link></div></header>
<div className="landing" id="home"><section className="landing-grid"><div className="marketing-copy"><span className="hero-label"><span/> {t.label}</span><h1>{t.h1}</h1><p>{t.intro}</p><div className="landing-actions"><Link className="gold" href="/manager/register">{t.register} <ArrowUpRight size={18}/></Link><ExplainerVideo/></div><div className="hero-assurances"><span><Check size={15}/> {t.trial}</span><span><Check size={15}/> {t.payment}</span></div><p className="landing-note">{t.note}</p></div><div className="landing-preview mascot-card-scene"><div className="mascot-card-stack"><img className="rezix-mascot" src="/media/rezix-rabbit-peek.png" alt="Rezix"/><div className="preview-card"><div className="marketing-card-heading"><span className="eyebrow">REZIX LOYALTY</span><span className="marketing-member"><ShieldCheck size={14}/> Digital</span></div><h2>{t.card}</h2><p>{t.cardp}</p><div className="preview-stamps">{Array.from({length:10},(_,i)=><div key={i} className={`preview-stamp rounded ${i<7?'filled':''}`}>{i<7?<Check size={21}/>:i+1}</div>)}</div><div className="preview-reward"><Gift size={24}/><div><b>{t.reward}</b><span>7 / 10</span></div></div></div></div></div></section>
<section className="marketing-workflow" id="funktionen"><div className="marketing-section-intro"><span className="eyebrow">REZIX</span><h2>{t.steps}</h2><p>{t.stepsp}</p></div><div className="landing-features"><article><span className="marketing-feature-icon"><QrCode/></span><h3>{t.s1}</h3></article><article><span className="marketing-feature-icon"><Scissors/></span><h3>{t.s2}</h3></article><article><span className="marketing-feature-icon"><Gift/></span><h3>{t.s3}</h3></article></div></section>
<section className="marketing-management" id="ueber-uns"><div><span className="eyebrow">REZIX LOYALTY</span><h2>{t.management}</h2><Link className="text-link" href="/manager/register">{t.register} <ArrowUpRight size={17}/></Link></div><div className="marketing-management-cards"><article><Users/><div><h3>Customers & Team</h3></div></article><article><Palette/><div><h3>Brand & Wallet</h3></div></article><article><Gift/><div><h3>Rewards</h3></div></article></div></section><section className="marketing-trial" id="preise"><h2>{t.cta}</h2><Link className="gold" href="/manager/register">{t.register} <ArrowUpRight size={18}/></Link></section></div></main>}
