'use client';
import { useState } from 'react';
import CustomerDesignFields from './CustomerDesignFields';
import { customerBackground,defaultCustomerDesign,type CustomerDesign } from '@/lib/customer-design';
import { Gift,Palette,Scissors } from 'lucide-react';

type Props={business:{customerDesign:CustomerDesign;name:string;rewardTarget:number;rewardText:string;logoUrl:string|null;stampUrl:string|null;cardTitle:string;cardSubtitle:string;primaryColor:string;stampShape:'circle'|'rounded'|'square'}};
export default function LoyaltyDesigner({business}:Props){
 const [design,setDesign]=useState(business.customerDesign||defaultCustomerDesign);
 const [target,setTarget]=useState(business.rewardTarget);const [reward,setReward]=useState(business.rewardText);const [title,setTitle]=useState(business.cardTitle);const [subtitle,setSubtitle]=useState(business.cardSubtitle);const [color,setColor]=useState(business.primaryColor);const [shape,setShape]=useState(business.stampShape);
 return <section className="panel loyalty-designer"><div className="panel-head"><div><h2><Palette size={20}/> Karten & Belohnungen</h2><p className="muted">Passe die Kundenkarte deines Salons an. Änderungen gelten automatisch für alle Kundenkarten.</p></div></div><div className="designer-grid"><form className="stack-form designer-form" method="post" action="/api/manager/loyalty-config" encType="multipart/form-data"><div className="form-split"><div><label>Anzahl der Stempel</label><input name="rewardTarget" type="number" min="2" max="30" value={target} onChange={e=>setTarget(Number(e.target.value)||2)} required/></div><div><label>Stempel-Form</label><select name="stampShape" value={shape} onChange={e=>setShape(e.target.value as any)}><option value="circle">Kreis</option><option value="rounded">Abgerundet</option><option value="square">Quadrat</option></select></div></div><label>Belohnung</label><input name="rewardText" value={reward} onChange={e=>setReward(e.target.value)} maxLength={160} required/><label>Kartentitel</label><input name="cardTitle" value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} required/><label>Untertitel</label><input name="cardSubtitle" value={subtitle} onChange={e=>setSubtitle(e.target.value)} maxLength={160} required/><label>Akzentfarbe</label><div className="color-control"><input name="primaryColor" type="color" value={color} onChange={e=>setColor(e.target.value)}/><input value={color} onChange={e=>setColor(e.target.value)} pattern="#[0-9A-Fa-f]{6}" aria-label="Hex-Farbe"/></div><label>Neues Salon-Logo (optional)</label><input name="logo" type="file" accept="image/png,image/jpeg,image/webp"/><label>Neuer Stempel (optional)</label><input name="stamp" type="file" accept="image/png,image/jpeg,image/webp"/><CustomerDesignFields design={design} onChange={setDesign}/><button className="gold" type="submit">Änderungen speichern</button></form><div className="designer-preview" style={{...customerBackground(design),'--preview-color':color} as React.CSSProperties}><span className="eyebrow">LIVE-VORSCHAU</span><div className="preview-card"><div className="card-head"><div>{business.logoUrl&&<img className="preview-logo" src={business.logoUrl} alt=""/>}<small>{title}</small><h3>{business.name}</h3><p>{subtitle}</p></div><b style={{color}}>{Math.min(6,target)}/{target}</b></div><div className="preview-stamps">{Array.from({length:Math.min(target,10)}).map((_,i)=><div key={i} className={`preview-stamp ${shape} ${i<Math.min(6,target)?'filled':''}`} style={i<Math.min(6,target)?{background:color,borderColor:color}:{}}>{i<Math.min(6,target)?(business.stampUrl?<img src={business.stampUrl} alt=""/>:<Scissors size={14}/>):i+1}</div>)}</div><div className="preview-reward"><Gift size={18} style={{color}}/><div><b>{reward}</b><span>Nächste Belohnung</span></div></div></div></div></div></section>
}
