'use client';
import {useMemo,useState} from 'react';
import CustomerDesignFields from './CustomerDesignFields';
import {defaultCustomerDesign,type CustomerDesign} from '@/lib/customer-design';
import {Check,Gift,Palette,Smartphone,Star,Heart,Coffee,Scissors,ImageOff} from 'lucide-react';

type Props={business:{customerDesign:CustomerDesign;name:string;rewardTarget:number;rewardText:string;logoUrl:string|null;stampUrl:string|null;cardTitle:string;cardSubtitle:string;primaryColor:string;stampShape:'circle'|'rounded'|'square'}};
type Platform='apple'|'google';
const stampIcons={check:Check,star:Star,heart:Heart,gift:Gift,coffee:Coffee,scissors:Scissors} as const;
export default function LoyaltyDesigner({business}:Props){
 const [design,setDesign]=useState(business.customerDesign||defaultCustomerDesign),[target,setTarget]=useState(business.rewardTarget),[reward,setReward]=useState(business.rewardText),[title,setTitle]=useState(business.cardTitle),[subtitle,setSubtitle]=useState(business.cardSubtitle),[color,setColor]=useState(business.primaryColor),[platform,setPlatform]=useState<Platform>('apple'),[logoRemoved,setLogoRemoved]=useState(false),[logoPreview,setLogoPreview]=useState<string|null>(business.logoUrl);
 const filled=Math.min(3,target),stamps=useMemo(()=>Array.from({length:Math.min(target,10)}),[target]); const StampIcon=stampIcons[design.stampSymbol||'check'];
 const imageStyle=design.mode==='image'&&design.imageUrl?{backgroundImage:`url(${JSON.stringify(design.imageUrl)})`,backgroundPosition:`${design.positionX??50}% ${design.positionY??50}%`,backgroundSize:design.size,backgroundRepeat:'no-repeat'}:{};
 return <section className="program-editor"><div className="program-editor-head"><div><span className="eyebrow">TREUEPROGRAMM</span><h1>Karte gestalten</h1><p className="muted">Die Live-Vorschau orientiert sich an der echten Wallet-Darstellung. Es werden nur Optionen angeboten, die auf der jeweiligen Karte sinnvoll abbildbar sind.</p></div><div className="program-status"><span className="status-dot"/> Aktiv</div></div>
 <div className="program-editor-grid"><form className="program-editor-form" method="post" action="/api/manager/loyalty-config" encType="multipart/form-data">
 <div className="editor-section"><div className="editor-section-title"><Gift size={18}/><div><b>Belohnung</b><span>Stempelziel und Symbol</span></div></div><div className="form-split"><div><label>Anzahl der Stempel</label><input name="rewardTarget" type="number" min="2" max="30" value={target} onChange={e=>setTarget(Number(e.target.value)||2)} required/></div><div><label>Stempel-Symbol</label><div className="stamp-symbol-grid">{Object.entries(stampIcons).map(([key,Icon])=><button type="button" key={key} className={(design.stampSymbol||'check')===key?'active':''} onClick={()=>setDesign({...design,stampSymbol:key as CustomerDesign['stampSymbol']})}><Icon size={18}/></button>)}</div><input type="hidden" name="stampSymbol" value={design.stampSymbol||'check'}/><input type="hidden" name="stampShape" value="circle"/></div></div><label>Belohnung</label><input name="rewardText" value={reward} onChange={e=>setReward(e.target.value)} maxLength={160} required/></div>
 <div className="editor-section"><div className="editor-section-title"><Smartphone size={18}/><div><b>Kartendetails</b><span>Texte auf der Wallet-Karte</span></div></div><label>Kartentitel</label><input name="cardTitle" value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} required/><label>Untertitel</label><input name="cardSubtitle" value={subtitle} onChange={e=>setSubtitle(e.target.value)} maxLength={160} required/></div>
 <div className="editor-section"><div className="editor-section-title"><Palette size={18}/><div><b>Look & Feel</b><span>Logo, Farbe und Wallet-Bild</span></div></div><label>Akzentfarbe</label><div className="color-control"><input name="primaryColor" type="color" value={color} onChange={e=>setColor(e.target.value)}/><input value={color} onChange={e=>setColor(e.target.value)} pattern="#[0-9A-Fa-f]{6}" aria-label="Hex-Farbe"/></div><label>Neues Betriebs-Logo</label><input name="logo" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f){setLogoRemoved(false);setLogoPreview(URL.createObjectURL(f))}}}/>{logoPreview&&!logoRemoved&&<button className="remove-image-button" type="button" onClick={()=>{setLogoRemoved(true);setLogoPreview(null)}}><ImageOff size={16}/> Logo entfernen</button>}<input type="hidden" name="removeLogo" value={logoRemoved?'on':''}/><CustomerDesignFields design={design} onChange={setDesign}/></div>
 <div className="editor-savebar"><span><Check size={16}/> Vorschau vor Veröffentlichung prüfen</span><button className="gold" type="submit">Änderungen speichern</button></div></form>
 <aside className="wallet-live-panel"><div className="wallet-live-head"><div><span className="live-pill"><i/> LIVE</span><b>Wallet-Vorschau</b></div><span className="muted">Plattformgetreu</span></div><div className="preview-switch"><button type="button" className={platform==='apple'?'active':''} onClick={()=>setPlatform('apple')}>Apple Wallet</button><button type="button" className={platform==='google'?'active':''} onClick={()=>setPlatform('google')}>Google Wallet</button></div>
 {platform==='apple'?<div className="apple-wallet-real"><div className="apple-wallet-top" style={{background:color}}>{logoPreview&&!logoRemoved?<img src={logoPreview} alt=""/>:<span/>}<b>{title}</b></div><div className="apple-wallet-strip" style={imageStyle}><div className="apple-primary"><strong>{filled} / {target}</strong><span>STEMPEL</span></div></div><div className="apple-wallet-bottom" style={{background:color}}><div><small>BELOHNUNG</small><b>{reward}</b></div><div><small>MITGLIED</small><b>Max Mustermann</b></div><div className="fake-qr-grid"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><span className="fake-code">RZX-DEMO</span></div></div>:<div className="google-wallet-real" style={{borderTopColor:color}}><div className="google-card-head">{logoPreview&&!logoRemoved&&<img src={logoPreview} alt=""/>}<div><small>{title}</small><b>{business.name}</b></div></div>{design.mode==='image'&&design.imageUrl&&<div className="google-hero" style={imageStyle}/>}<div className="google-progress"><strong>{filled} / {target}</strong><span>Stempel gesammelt</span></div><div className="google-stamps">{stamps.map((_,i)=><span key={i} className={i<filled?'filled':''} style={i<filled?{background:color}:undefined}>{i<filled?<StampIcon size={16}/>:i+1}</span>)}</div><div className="google-reward"><Gift size={18}/><div><small>BELOHNUNG</small><b>{reward}</b></div></div><div className="google-barcode">▥ ▦ ▤ ▥ ▦</div></div>}
 <p className="wallet-live-note">Apple und Google verwenden unterschiedliche Kartenlayouts. Die Vorschau zeigt deshalb bewusst zwei verschiedene Darstellungen.</p></aside></div></section>
}
