import ManagerPrivacy from '@/components/ManagerPrivacy';
import { billingStatusLabel } from '@/lib/billing';
import { listActorSessions } from '@/lib/auth-store';
import SessionSecurityCard from '@/components/SessionSecurityCard';
import { requireManager } from '@/lib/auth';
import { getManagerViewData } from '@/lib/store';
import { Scissors,Gift,Users,History,UserPlus,ExternalLink,CreditCard } from 'lucide-react';
import DashboardShell from '@/components/DashboardShell';
import LoyaltyDesigner from '@/components/LoyaltyDesigner';
import Link from 'next/link';
import BusinessSetupChecklist from '@/components/BusinessSetupChecklist';
import BusinessProfileSettings from '@/components/BusinessProfileSettings';

export default async function ManagerPage({searchParams,view='overview'}:{searchParams:Promise<Record<string,string|undefined>>,view?:string}){
 const s=await requireManager();const q=await searchParams;const page=Math.max(1,Math.min(100000,Number.parseInt(q.page||'1',10)||1));const db=await getManagerViewData(s.businessId!,view,page);
 if(!db.business)return <main><section className="join"><div className="join-card"><h1>Betrieb nicht verfügbar</h1></div></section></main>;
 return <DashboardShell role="manager" name={s.name} businessName={db.business.name} logoUrl={db.business.logoUrl}>
 <section id="overview" className="dashboard-hero"><div><span className="eyebrow">BETRIEB ÜBERSICHT</span><h1>{{"overview": "Dein Betrieb im Überblick", "friseure": "Dein Team", "customers": "Kundenübersicht", "loyalty": "Karten & Belohnungen", "settings": "Betriebs-Einstellungen"}[view]}</h1><p>{db.business.name} · {db.business.billingPlan.toUpperCase()} · {billingStatusLabel(db.business.subscriptionStatus)}{db.business.subscriptionStatus==='trialing'&&db.business.trialEndsAt?` · ${Math.max(0,Math.ceil((new Date(db.business.trialEndsAt).getTime()-Date.now())/86400000))} Tage Testphase verbleibend`:null}</p></div><div className="page-actions"><a className="secondary link-button" href={`/s/${db.business.slug}`} target="_blank"><ExternalLink size={15}/> Kundenkarte öffnen</a></div></section>
 {view==='overview'&&(<><BusinessSetupChecklist business={db.business} staffCount={db.staffCount}/><div className="metrics dashboard-metrics"><Metric label="Besuche diesen Monat" value={String(db.visitsMonth)} icon={<Scissors/>}/><Metric label="Kunden" value={String(db.totalCustomers)} icon={<Users/>}/><Metric label="Mitarbeiter" value={String(db.staffCount)} icon={<UserPlus/>}/><Metric label="Eingelöste Belohnungen" value={String(db.rewards)} icon={<Gift/>}/><Metric label="Aktiv in den letzten 30 Tagen" value={String(db.activeCustomers)} icon={<Users/>}/><Metric label="Tarifstatus" value={billingStatusLabel(db.business.subscriptionStatus)} icon={<CreditCard/>}/></div></>)}
 {q.teamSaved&&<div className="success">Team-Zugang aktualisiert.</div>}{q.teamError&&<div className="alert">Aktion nicht möglich. Prüfe Tariflimit und Zugang.</div>}{q.customerSaved&&<div className="success">Kunde aktualisiert.</div>}{q.customerError&&<div className="alert">Kundendaten konnten nicht gespeichert werden.</div>}{q.privacyCreated&&<div className="success">Löschanfrage zur Prüfung angelegt.</div>}{q.privacyUpdated&&<div className="success">Datenschutzanfrage bearbeitet.</div>}{q.privacyError&&<div className="alert">Datenschutzanfrage konnte nicht abgeschlossen werden.</div>}
 {q.profileSaved&&<div className="success">Betriebsprofil gespeichert.</div>}{q.profileError&&<div className="alert">Betriebsprofil konnte nicht gespeichert werden.</div>}{q.billingBlocked&&<div className="alert">Diese Aktion ist mit deinem aktuellen Tarif derzeit nicht verfügbar. Prüfe deinen Tarif unter <a href="/manager/billing">Tarif & Abrechnung</a>.</div>}
 {q.configSaved&&<div className="success">Treuekarte und Belohnung wurden aktualisiert. Die Änderungen sind sofort für alle Kunden sichtbar.</div>}{q.configError&&<div className="alert">Die Karten-Einstellungen konnten nicht gespeichert werden. Prüfe die Eingaben.</div>}{q.configUpload&&<div className="alert">Logo oder Stempel konnte nicht hochgeladen werden. Verwende PNG, JPG oder WEBP bis 2 MB.</div>}
 <div className="dashboard-page-section">
  {view==='friseure'&&(<section id="friseure" className="panel"><div className="section-kicker">TEAM</div><h2>Dein Team</h2><div className="team-list">{db.staff.length===0?<p className="muted">Noch keine Mitarbeiter angelegt.</p>:db.staff.map(staff=><div className="row" key={staff.id}><div><b>{staff.name}</b><span>{staff.email} · {staff.active?'Aktiv':'Deaktiviert'} · {staff.email_verified_at?'E-Mail bestätigt':'E-Mail ausstehend'}</span></div><form method="post" action="/api/manager/team"><input type="hidden" name="staffId" value={staff.id}/><button className="secondary" name="action" value={staff.active?'disable':'activate'}>{staff.active?'Deaktivieren':'Aktivieren'}</button></form></div>)}</div><h3>Mitarbeiter-Zugang erstellen</h3><p className="muted">Nur Mitarbeiter dieses Betriebs erhalten Zugriff auf dessen Kundenkarten.</p>{q.friseurAdded&&<div className="success">Mitarbeiter-Zugang wurde erstellt. Die E-Mail-Adresse muss vor der ersten Anmeldung bestätigt werden.</div>}{q.mailError&&<div className="alert">Der Zugang wurde erstellt, aber die Verifizierungs-E-Mail konnte nicht versendet werden.</div>}{q.friseurError&&<div className="alert">Bitte gültige Daten und mindestens 12 Zeichen als Passwort eingeben.</div>}{q.friseurExists&&<div className="alert">Diese E-Mail-Adresse existiert bereits.</div>}<form className="stack-form" method="post" action="/api/friseur/create"><label>Name</label><input name="name" required/><label>E-Mail</label><input name="email" type="email" required/><label>Temporäres Passwort</label><input name="password" type="password" minLength={12} required/><input type="hidden" name="role" value="friseur"/><button className="gold" type="submit">Zugang erstellen</button></form></section>)}
  {view==='customers'&&(<section id="customers" className="panel"><div className="section-kicker">KUNDEN</div><h2>Kundenübersicht</h2>{db.customers.length===0?<div className="empty-block"><Users size={36}/><b>Noch keine Kunden</b><span>Kunden erscheinen hier erst nach einer echten Registrierung.</span></div>:<div className="attention customer-list-scroll">{db.customers.map(c=><div className="row" key={c.id}><div className="avatar sm">{c.name.slice(0,1).toUpperCase()}</div><div><b>{c.name}</b><span>{c.email||c.code} · {c.stamps}/{db.business!.rewardTarget} Stempel</span><details><summary>Kunde verwalten</summary><form className="stack-form" method="post" action="/api/manager/customer/update"><input type="hidden" name="customerId" value={c.id}/><label htmlFor={'customer-'+c.id}>Name</label><input id={'customer-'+c.id} name="name" defaultValue={c.name} maxLength={100} required/><div className="page-actions"><button className="secondary" name="action" value="edit">Speichern</button><a className="secondary" href={`/api/manager/customer/export?id=${c.id}`}>Daten exportieren</a><button className="secondary" name="action" value="erasure">Löschanfrage erfassen</button></div></form></details></div></div>)}</div>}<nav className="pagination" aria-label="Kundenseiten">{page>1&&<Link className="secondary" href={`/manager/customers?page=${page-1}`}>Zurück</Link>}<span>Seite {page} · {db.totalCustomers} Kunden</span>{page*25<db.totalCustomers&&<Link className="secondary" href={`/manager/customers?page=${page+1}`}>Weiter</Link>}</nav></section>)}
 </div>
 {view==='loyalty'&&(<section id="loyalty" className="dashboard-section"><div className="section-heading"><div><span className="section-kicker">LOYALTY</span><h2>Karten & Belohnungen</h2></div><span className="section-note">Änderungen gelten sofort für alle Kunden</span></div><LoyaltyDesigner business={db.business}/></section>)}
 {view==='settings'&&(<><BusinessProfileSettings business={db.business}/><section id="settings" className="panel quick dashboard-section"><div className="section-kicker">LOYALTY & BRANDING</div><h2>Karte & Kundenauftritt</h2><p className="muted">Logo, Stempel, Hintergrund, Farben und Belohnungen bearbeitest du im Karten-Designer.</p><Link className="secondary link-button" href="/manager/loyalty">Kartendesign bearbeiten</Link><div className="brand-config">{db.business.logoUrl&&<div><span>Betriebs-Logo</span><img src={db.business.logoUrl} alt="Logo"/></div>}{db.business.stampUrl&&<div><span>Aktueller Stempel</span><img src={db.business.stampUrl} alt="Stempel"/></div>}</div><div className="quick-grid"><Info icon={<Gift/>} title="Belohnung" text={db.business.rewardText}/><Info icon={<Scissors/>} title="Ziel" text={`${db.business.rewardTarget} Stempel`}/><Info icon={<History/>} title="Gespeicherte Besuche" text={String(db.visitCount)}/></div></section><div className="settings-stack"><SessionSecurityCard sessions={await listActorSessions('manager',s.sub)} currentJti={s.jti} revoked={!!q.sessionsRevoked}/><ManagerPrivacy businessId={s.businessId!}/></div></>)}
 {view==='overview'&&<div className="workspace-grid"><Link className="workspace-card" href="/manager/friseure"><span className="section-kicker">BETRIEB</span><h2>Dein Team</h2><p>Zugänge für dein Team verwalten.</p><span className="workspace-card-action">Bereich öffnen →</span></Link><Link className="workspace-card" href="/manager/customers"><span className="section-kicker">BETRIEB</span><h2>Kundenübersicht</h2><p>Kunden und ihren Treuestatus ansehen.</p><span className="workspace-card-action">Bereich öffnen →</span></Link><Link className="workspace-card" href="/manager/loyalty"><span className="section-kicker">BETRIEB</span><h2>Karten & Belohnungen</h2><p>Deine digitale Treuekarte gestalten.</p><span className="workspace-card-action">Bereich öffnen →</span></Link><Link className="workspace-card" href="/manager/settings"><span className="section-kicker">BETRIEB</span><h2>Betriebs-Einstellungen</h2><p>Branding und Betriebsinformationen ansehen.</p><span className="workspace-card-action">Bereich öffnen →</span></Link></div>}</DashboardShell>;
}
function Metric({label,value,icon}:{label:string,value:string,icon:React.ReactNode}){return <div className="metric"><div className="iconbox">{icon}</div><span>{label}</span><b>{value}</b><small>Live</small></div>}
function Info({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="info"><div className="iconbox">{icon}</div><div><b>{title}</b><span>{text}</span></div></div>}
