'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {INDUSTRIES,industryDefaults} from '@/lib/industries';
import {ArrowLeft,ArrowRight,Building2,Gift,MapPin,Palette,Check} from 'lucide-react';

export default function MultiBranchRegistration({error}:{error?:string}){
 const [step,setStep]=useState(0);const [industry,setIndustry]=useState('hair_beauty');const defaults=useMemo(()=>industryDefaults(industry),[industry]);
 const steps=['Branche','Treueprogramm','Betrieb','Manager'];
 return <div className="onboarding-shell"><div className="onboarding-progress">{steps.map((label,i)=><div key={label} className={`onboarding-step ${i<=step?'active':''}`}><span>{i<step?<Check size={14}/>:i+1}</span><b>{label}</b></div>)}</div>
 <form className="join-card onboarding-card" method="post" action="/api/manager/register">
  <input type="hidden" name="industry" value={industry}/><input type="hidden" name="programType" value="stamps"/>
  {error&&<div className="alert">{error==='limited'?'Zu viele Versuche. Bitte später erneut versuchen.':error==='unavailable'?'E-Mail-Adresse oder Betriebs-Adresse bereits vergeben.':'Registrierung nicht möglich. Bitte prüfe deine Eingaben.'}</div>}
  <div className={step===0?'onboarding-pane':'hidden'}><span className="eyebrow">SCHRITT 1 VON 4</span><h1>Welche Branche passt zu deinem Betrieb?</h1><p>Rezix passt Texte und Empfehlungen automatisch an deinen Betrieb an.</p><div className="industry-grid">{INDUSTRIES.map(([id,label])=><button type="button" key={id} onClick={()=>setIndustry(id)} className={`industry-option ${industry===id?'selected':''}`}><Building2 size={20}/><span>{label}</span></button>)}</div></div>
  <div className={step===1?'onboarding-pane':'hidden'}><span className="eyebrow">SCHRITT 2 VON 4</span><h1>Dein Treueprogramm</h1><p>Starte mit einer digitalen Stempelkarte. Weitere Programmtypen können später ergänzt werden.</p><div className="choice-card selected"><Gift/><div><b>Stempelkarte</b><span>Ein Besuch = ein Stempel. Bei voller Karte wird die Belohnung freigeschaltet.</span></div></div><label>Stempel bis zur Belohnung</label><input name="rewardTarget" type="number" min="2" max="30" defaultValue={defaults.target} key={industry+'-target'} required/><label>Belohnung</label><input name="rewardText" maxLength={160} defaultValue={defaults.reward} key={industry+'-reward'} required/><label>Kartentitel</label><input name="cardTitle" maxLength={80} defaultValue={defaults.title} key={industry+'-title'} required/></div>
  <div className={step===2?'onboarding-pane':'hidden'}><span className="eyebrow">SCHRITT 3 VON 4</span><h1>Dein Betrieb</h1><div className="form-split"><div><label>Betriebsname</label><input name="name" maxLength={120} autoComplete="organization" required/></div><div><label>Rezix-Adresse</label><input name="slug" maxLength={60} pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="mein-betrieb" required/></div></div><label>Standortname</label><input name="locationName" maxLength={120} placeholder="z. B. Hauptfiliale Wien"/><label>Straße & Hausnummer</label><input name="street" maxLength={160}/><div className="form-split"><div><label>PLZ</label><input name="postalCode" maxLength={20}/></div><div><label>Ort</label><input name="city" maxLength={100}/></div></div><label>Website (optional)</label><input name="website" type="url" placeholder="https://"/><div className="onboarding-tip"><MapPin size={18}/> Diese Daten kannst du später jederzeit in den Einstellungen ändern.</div></div>
  <div className={step===3?'onboarding-pane':'hidden'}><span className="eyebrow">SCHRITT 4 VON 4</span><h1>Manager-Zugang erstellen</h1><label>Dein Name</label><input name="managerName" maxLength={100} autoComplete="name" required/><label>E-Mail-Adresse</label><input name="email" type="email" maxLength={160} autoComplete="email" required/><label>Passwort</label><input name="password" type="password" minLength={12} maxLength={128} autoComplete="new-password" required/><small>Mindestens 12 Zeichen.</small><label className="checkline"><input type="checkbox" name="terms" required/><span>Ich akzeptiere die <Link href="/agb" target="_blank">AGB</Link> und habe die <Link href="/datenschutz" target="_blank">Datenschutzerklärung</Link> gelesen.</span></label></div>
  <div className="onboarding-actions">{step>0&&<button type="button" className="secondary" onClick={()=>setStep(step-1)}><ArrowLeft size={16}/> Zurück</button>}<span/>{step<3?<button type="button" className="gold" onClick={()=>setStep(step+1)}>Weiter <ArrowRight size={16}/></button>:<button className="gold" type="submit">Kostenlos starten</button>}</div>
 </form></div>
}
