import { requireManager } from '@/lib/auth';
import { getDashboardData } from '@/lib/store';
import { Scissors,Gift,Users,History,UserPlus,ExternalLink,CreditCard } from 'lucide-react';
import LoyaltyDesigner from '@/components/LoyaltyDesigner';
export const dynamic='force-dynamic';

export default async function ManagerPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const s=await requireManager();const db=await getDashboardData(s.businessId!);const q=await searchParams;
 if(!db.business)return <main><section className="join"><div className="join-card"><h1>Salon nicht verfügbar</h1></div></section></main>;
 return <main><header className="topbar"><div className="brand"><img src="/rezix-logo.svg" alt="Rezix"/><div><b>REZIX</b><span>MANAGER</span></div></div><form method="post" action="/api/logout"><button type="submit" className="secondary">Abmelden</button></form></header><div className="shell"><div className="page-title"><div><span className="eyebrow">SALON ÜBERSICHT</span><h1>{db.business.name}</h1><p>Kunden, Friseure, Treuekarte und Belohnungen an einem Ort verwalten.</p></div><div className="page-actions"><a className="secondary link-button" href="/manager/billing"><CreditCard size={15}/> Tarif & Abrechnung</a><a className="secondary link-button" href={`/s/${db.business.slug}`} target="_blank"><ExternalLink size={15}/> Kundenkarte öffnen</a></div></div>
 <div className="metrics"><Metric label="Besuche heute" value={String(db.visitsToday)} icon={<Scissors/>}/><Metric label="Kunden" value={String(db.totalCustomers)} icon={<Users/>}/><Metric label="Friseure" value={String(db.staffCount)} icon={<UserPlus/>}/><Metric label="Stempelziel" value={String(db.business.rewardTarget)} icon={<Gift/>}/></div>
 {q.billingBlocked&&<div className="alert">Diese Aktion ist mit deinem aktuellen Tarif derzeit nicht verfügbar. Prüfe deinen Tarif und das Friseur-Limit unter <a href="/manager/billing">Tarif & Abrechnung</a>.</div>}
 {q.configSaved&&<div className="success">Treuekarte und Belohnung wurden aktualisiert. Die Änderungen sind sofort für alle Kunden sichtbar.</div>}{q.configError&&<div className="alert">Die Karten-Einstellungen konnten nicht gespeichert werden. Prüfe die Eingaben.</div>}{q.configUpload&&<div className="alert">Logo oder Stempel konnte nicht hochgeladen werden. Verwende PNG, JPG oder WEBP bis 2 MB.</div>}
 <div className="owner-grid"><section className="panel"><h2>Friseur-Zugang erstellen</h2><p className="muted">Nur Friseure dieses Salons erhalten Zugriff auf dessen Kundenkarten.</p>{q.friseurAdded&&<div className="success">Friseur-Zugang wurde erstellt. Die E-Mail-Adresse muss vor der ersten Anmeldung bestätigt werden.</div>}{q.mailError&&<div className="alert">Der Zugang wurde erstellt, aber die Verifizierungs-E-Mail konnte nicht versendet werden.</div>}{q.friseurError&&<div className="alert">Bitte gültige Daten und mindestens 12 Zeichen als Passwort eingeben.</div>}{q.friseurExists&&<div className="alert">Diese E-Mail-Adresse existiert bereits.</div>}<form className="stack-form" method="post" action="/api/friseur/create"><label>Name</label><input name="name" required/><label>E-Mail</label><input name="email" type="email" required/><label>Temporäres Passwort</label><input name="password" type="password" minLength={12} required/><input type="hidden" name="role" value="friseur"/><button className="gold" type="submit">Zugang erstellen</button></form></section><section className="panel"><h2>Kunden</h2>{db.customers.length===0?<div className="empty-block"><Users size={36}/><b>Noch keine Kunden</b><span>Kunden erscheinen hier erst nach einer echten Registrierung.</span></div>:<div className="attention">{db.customers.map(c=><div className="row" key={c.id}><div className="avatar sm">{c.name.slice(0,1).toUpperCase()}</div><div><b>{c.name}</b><span>{c.email||c.code} · {c.stamps}/{db.business!.rewardTarget} Stempel</span></div></div>)}</div>}</section></div>
 <LoyaltyDesigner business={db.business}/>
 <section className="panel quick"><h2>Salon-Konfiguration</h2><div className="brand-config">{db.business.logoUrl&&<div><span>Salon-Logo</span><img src={db.business.logoUrl} alt="Logo"/></div>}{db.business.stampUrl&&<div><span>Aktueller Stempel</span><img src={db.business.stampUrl} alt="Stempel"/></div>}</div><div className="quick-grid"><Info icon={<Gift/>} title="Belohnung" text={db.business.rewardText}/><Info icon={<Scissors/>} title="Ziel" text={`${db.business.rewardTarget} Stempel`}/><Info icon={<History/>} title="Gespeicherte Besuche" text={String(db.visitCount)}/></div></section>
 </div></main>;
}
function Metric({label,value,icon}:{label:string,value:string,icon:React.ReactNode}){return <div className="metric"><div className="iconbox">{icon}</div><span>{label}</span><b>{value}</b><small>Live</small></div>}
function Info({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="info"><div className="iconbox">{icon}</div><div><b>{title}</b><span>{text}</span></div></div>}
