import { requireManager } from '@/lib/auth';
import { getDashboardData,listPrivacyRequests } from '@/lib/store';
import { recentAudit } from '@/lib/security';
import { listActorSessions } from '@/lib/auth-store';
import SessionSecurityCard from '@/components/SessionSecurityCard';
import { Scissors,Gift,Users,History,UserPlus,ShieldCheck,ExternalLink,Trash2,FileDown,CreditCard } from 'lucide-react';
export const dynamic='force-dynamic';
export default async function ManagerPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const s=await requireManager();const [db,auditRows,privacyRows,sessions]=await Promise.all([getDashboardData(s.businessId!),recentAudit(s.businessId!,20),listPrivacyRequests(s.businessId!),listActorSessions('manager',s.sub)]);const q=await searchParams;
 if(!db.business)return <main><section className="join"><div className="join-card"><h1>Salon nicht verfügbar</h1></div></section></main>;
 return <main><header className="topbar"><div className="brand">{db.business.logoUrl?<img src={db.business.logoUrl} alt={db.business.name}/>:<img src="/icon.svg" alt="Rezix"/>}<div><b>REZIX</b><span>MANAGER</span></div></div><form method="post" action="/api/logout"><button type="submit" className="secondary">Abmelden</button></form></header><div className="shell"><div className="page-title"><div><span className="eyebrow">BUSINESS OVERVIEW</span><h1>{db.business.name}</h1><p>Alle Kennzahlen und Zugänge gehören ausschließlich zu diesem Salon.</p></div><div className="page-actions"><a className="secondary link-button" href="/manager/billing"><CreditCard size={15}/> Abonnement</a><a className="secondary link-button" href={`/s/${db.business.slug}`} target="_blank"><ExternalLink size={15}/> Kundenkarte</a><div className="pill"><ShieldCheck size={15}/> Manager</div></div></div>
 <div className="metrics"><Metric label="Besuche heute" value={String(db.visitsToday)} icon={<Scissors/>}/><Metric label="Kunden" value={String(db.totalCustomers)} icon={<Users/>}/><Metric label="Friseure" value={String(db.staffCount)} icon={<UserPlus/>}/><Metric label="Belohnungsziel" value={String(db.business.rewardTarget)} icon={<Gift/>}/></div>
 {q.billingBlocked&&<div className="alert">Dein Tarif erlaubt diese Aktion derzeit nicht. Prüfe Testphase, Zahlungsstatus oder Friseur-Limit unter <a href="/manager/billing">Abonnement & Rechnungen</a>.</div>}<div className="owner-grid"><section className="panel"><h2>Friseur-Zugang erstellen</h2><p className="muted">Nur Friseure dieses Salons erhalten Zugriff auf dessen Kundenkarten.</p>{q.friseurAdded&&<div className="success">Friseur-Zugang wurde erstellt. Die E-Mail-Adresse muss vor der ersten Anmeldung bestätigt werden.</div>}{q.mailError&&<div className="alert">Der Zugang wurde erstellt, aber die Verifizierungs-E-Mail konnte nicht versendet werden.</div>}{q.friseurError&&<div className="alert">Bitte gültige Daten und mindestens 12 Zeichen als Passwort eingeben.</div>}{q.friseurExists&&<div className="alert">Diese E-Mail-Adresse existiert bereits.</div>}<form className="stack-form" method="post" action="/api/friseur/create"><label>Name</label><input name="name" required/><label>E-Mail</label><input name="email" type="email" required/><label>Temporäres Passwort</label><input name="password" type="password" minLength={12} required/><input type="hidden" name="role" value="friseur"/><button className="gold" type="submit">Zugang erstellen</button></form></section><section className="panel"><h2>Kunden</h2>{db.customers.length===0?<div className="empty-block"><Users size={36}/><b>Noch keine Kunden</b><span>Die Liste bleibt leer, bis sich echte Kunden registrieren.</span></div>:<div className="attention">{db.customers.map(c=><div className="row" key={c.id}><div className="avatar sm">{c.name.slice(0,1).toUpperCase()}</div><div><b>{c.name}</b><span>{c.code} · {c.stamps}/{db.business!.rewardTarget} Stempel</span></div></div>)}</div>}</section></div>
 <section className="panel quick"><h2><ShieldCheck size={20}/> Datenschutz-Anfragen</h2><p className="muted">Lösch- und Auskunftsanfragen werden salonbezogen dokumentiert. Prüfe die Identität und rechtliche Aufbewahrungspflichten, bevor du einen Löschantrag abschließt.</p>{q.privacyUpdated&&<div className="success">Datenschutz-Anfrage wurde aktualisiert.</div>}{q.privacyError&&<div className="alert">Die Anfrage konnte nicht aktualisiert werden.</div>}{privacyRows.length===0?<div className="empty-block"><ShieldCheck size={32}/><b>Keine Datenschutz-Anfragen</b><span>Neue Anfragen von Kunden erscheinen hier.</span></div>:<div className="privacy-list">{privacyRows.map(r=><div className="privacy-row" key={r.id}><div className="privacy-main"><div className="iconbox">{r.requestType==='erasure'?<Trash2 size={18}/>:<FileDown size={18}/>}</div><div><b>{r.requestType==='erasure'?'Löschantrag':'Auskunftsantrag'} · {r.customerName}</b><span>{r.customerEmail||'Keine E-Mail'} · {new Date(r.requestedAt).toLocaleString('de-DE')}</span><small>Status: {r.status}</small></div></div>{r.status==='pending'&&<form className="privacy-resolution" method="post" action="/api/manager/privacy/resolve"><input type="hidden" name="requestId" value={r.id}/><input name="note" placeholder="Interne Notiz (optional)" maxLength={500}/><button className="gold" name="decision" value="completed" type="submit">Abschließen</button><button className="secondary" name="decision" value="rejected" type="submit">Ablehnen</button></form>}</div>)}</div>}</section>
 <section className="panel quick"><h2>Branding & Konfiguration</h2><div className="brand-config">{db.business.logoUrl&&<div><span>Logo</span><img src={db.business.logoUrl} alt="Logo"/></div>}{db.business.stampUrl&&<div><span>Stempel</span><img src={db.business.stampUrl} alt="Stempel"/></div>}</div><div className="quick-grid"><Info icon={<Gift/>} title="Belohnung" text={db.business.rewardText}/><Info icon={<Scissors/>} title="Ziel" text={`${db.business.rewardTarget} Stempel`}/><Info icon={<History/>} title="Gespeicherte Besuche" text={String(db.visitCount)}/></div></section>
 <SessionSecurityCard sessions={sessions} currentJti={s.jti} revoked={!!q.sessionsRevoked}/><section className="panel quick"><h2>Sicherheitsprotokoll</h2>{auditRows.length===0?<div className="empty-block"><ShieldCheck size={30}/><b>Noch keine Audit-Ereignisse</b><span>Sicherheitsrelevante Aktionen werden hier protokolliert.</span></div>:<div className="attention">{auditRows.map((a:any,i:number)=><div className="row" key={`${a.created_at}-${i}`}><div className="avatar sm"><ShieldCheck size={15}/></div><div><b>{auditLabel(String(a.action))}</b><span>{String(a.actor_type).toUpperCase()} · {new Date(a.created_at).toLocaleString('de-DE')}</span></div></div>)}</div>}</section>
 </div></main>;
}
function Metric({label,value,icon}:{label:string,value:string,icon:React.ReactNode}){return <div className="metric"><div className="iconbox">{icon}</div><span>{label}</span><b>{value}</b><small>Live</small></div>}
function Info({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="info"><div className="iconbox">{icon}</div><div><b>{title}</b><span>{text}</span></div></div>}
function auditLabel(a:string){const m:Record<string,string>={'auth.login.success':'Anmeldung erfolgreich','auth.login.failed':'Anmeldung fehlgeschlagen','auth.logout':'Abmeldung','friseur.created':'Friseur-Zugang erstellt','stamp.added':'Stempel hinzugefügt','stamp.failed.not_found':'Ungültiger Kundencode','kunde.registered':'Kunde registriert','business.created':'Salon erstellt','billing.checkout.created':'Stripe Checkout erstellt','billing.checkout.failed':'Stripe Checkout fehlgeschlagen','billing.portal.opened':'Stripe Kundenportal geöffnet','privacy.exported':'Kundendaten exportiert','privacy.erasure.requested':'Löschung beantragt','privacy.erasure.completed':'Löschung abgeschlossen','privacy.erasure.rejected':'Löschantrag abgelehnt'};return m[a]||a}
