import DashboardShell from '@/components/DashboardShell';
import { requireManager } from '@/lib/auth';
import { getBusinessById } from '@/lib/store';
import { BILLING_PLANS,billingOperational,billingStatusLabel,friseurLimitFor,planDefinition,trialActive } from '@/lib/billing';
import { ArrowLeft,Check,Clock3,CreditCard,ExternalLink,ShieldCheck } from 'lucide-react';
export const dynamic='force-dynamic';
export default async function BillingPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const s=await requireManager();const business=await getBusinessById(s.businessId!);const q=await searchParams;if(!business)return null;
 const trialDays=business.trialEndsAt?Math.max(0,Math.ceil((new Date(business.trialEndsAt).getTime()-Date.now())/86400000)):0;const currentPlan=planDefinition(business.billingPlan);const operational=billingOperational(business);const hasManagedSubscription=!!business.stripeSubscriptionId&&!['canceled','incomplete_expired'].includes(business.subscriptionStatus);
 return <DashboardShell role="manager" name={s.name} businessName={business.name}><div className="page-title"><div><span className="eyebrow">TARIF & ABRECHNUNG</span><h1>Dein Rezix Tarif</h1><p>Wähle den passenden Tarif für {business.name}. Zahlungsdaten werden sicher über unseren Zahlungsdienst verarbeitet.</p></div><div className={`billing-status ${operational?'ok':'warn'}`}><ShieldCheck size={16}/>{billingStatusLabel(business.subscriptionStatus)}</div></div>
 {q.checkout==='success'&&<div className="success">Zahlung abgeschlossen. Dein Tarif wird in wenigen Sekunden aktualisiert.</div>}{q.checkout==='cancelled'&&<div className="alert">Zahlung wurde abgebrochen. Es wurde kein neuer Tarif aktiviert.</div>}{q.manage&&<div className="alert">Für ein bestehendes Abonnement verwende bitte das Zahlungsportal.</div>}{q.error&&<div className="alert">Die Abrechnungsaktion konnte nicht abgeschlossen werden. Bitte später erneut versuchen.</div>}
 <section className="panel billing-current"><div><span className="eyebrow">AKTUELLER STATUS</span><h2>{business.billingPlan==='trial'?'Kostenlose Testphase':currentPlan?.name||business.billingPlan}</h2><p className="muted">{business.subscriptionStatus==='trialing'?(trialActive(business)?`Noch ${trialDays} Tag${trialDays===1?'':'e'} Testphase.`:'Die Testphase ist abgelaufen.'):`Status: ${billingStatusLabel(business.subscriptionStatus)}${business.cancelAtPeriodEnd?' · Kündigung zum Periodenende vorgemerkt':''}`}</p></div><div className="billing-facts"><span><Clock3 size={15}/>{business.subscriptionCurrentPeriodEnd?`Nächste Periode: ${new Date(business.subscriptionCurrentPeriodEnd).toLocaleDateString('de-DE')}`:business.trialEndsAt?`Testphase bis ${new Date(business.trialEndsAt).toLocaleDateString('de-DE')}`:'Keine Periode'}</span><span><CreditCard size={15}/> Friseur-Limit: {friseurLimitFor(business.billingPlan,business.subscriptionStatus)}</span></div>{business.stripeCustomerId&&<form method="post" action="/api/billing/portal"><button className="gold" type="submit"><ExternalLink size={16}/> Zahlungsportal öffnen</button></form>}</section>
 <div className="billing-grid">{BILLING_PLANS.map(p=><section className={`plan-card ${business.billingPlan===p.key?'selected':''}`} key={p.key}><div><span className="eyebrow">{p.name.toUpperCase()}</span><h2>{p.monthlyLabel}<small>/Monat</small></h2></div><div className="plan-features">{p.features.map(x=><span key={x}><Check size={15}/>{x}</span>)}</div><div className="plan-actions"><form method="post" action="/api/billing/checkout"><input type="hidden" name="plan" value={p.key}/><input type="hidden" name="interval" value="monthly"/><button className="gold full" type="submit" disabled={hasManagedSubscription}>Tarif wählen</button></form></div></section>)}</div>
 </DashboardShell>
}
