import DashboardShell from '@/components/DashboardShell';
import { requireManager } from '@/lib/auth';
import { getBusinessById } from '@/lib/store';
import { BILLING_PLANS,billingOperational,billingStatusLabel,friseurLimitFor,planDefinition,trialActive } from '@/lib/billing';
import { ArrowLeft,Check,Clock3,CreditCard,ExternalLink,ShieldCheck } from 'lucide-react';
export const dynamic='force-dynamic';
export default async function BillingPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const s=await requireManager();const business=await getBusinessById(s.businessId!);const q=await searchParams;if(!business)return null;
 const trialDays=business.trialEndsAt?Math.max(0,Math.ceil((new Date(business.trialEndsAt).getTime()-Date.now())/86400000)):0;const currentPlan=planDefinition(business.billingPlan);const operational=billingOperational(business);const hasManagedSubscription=!!business.stripeSubscriptionId&&!['canceled','incomplete_expired'].includes(business.subscriptionStatus);
 return <DashboardShell role="manager" name={s.name} businessName={business.name}><div className="page-title"><div><span className="eyebrow">TARIF & ABRECHNUNG</span><h1>Dein Rezix Tarif</h1><p>Wähle den passenden Tarif für {business.name}. Zahlungsdaten werden sicher über unseren Zahlungsdienst verarbeitet.</p></div><div className={`billing-status ${operational?'ok':'warn'}`}><ShieldCheck size={16}/>{billingStatusLabel(business.subscriptionStatus)}</div></div>
 {q.checkout==='success'&&<div className="success">Zahlung abgeschlossen. Dein Tarif wird in wenigen Sekunden aktualisiert.</div>}{q.checkout==='cancelled'&&<div className="alert">Zahlung wurde abgebrochen. Es wurde kein neuer Tarif aktiviert.</div>}{q.manage&&<div className="alert">Für ein bestehendes Abonnement verwende bitte das Zahlungsportal.</div>}{q.error&&<div className="alert">Die Abrechnungsaktion konnte nicht abgeschlossen werden. Bitte später erneut versuchen.</div>}
 <section className="panel billing-current"><div><span className="eyebrow">AKTUELLER STATUS</span><h2>{business.billingPlan==='trial'?'Kostenlose Testphase':currentPlan?.name||business.billingPlan}</h2><p className="muted">{business.subscriptionStatus==='trialing'?(trialActive(business)?`Noch ${trialDays} Tag${trialDays===1?'':'e'} Testphase.`:'Die Testphase ist abgelaufen.'):`Status: ${billingStatusLabel(business.subscriptionStatus)}${business.cancelAtPeriodEnd?' · Kündigung zum Periodenende vorgemerkt':''}`}</p></div><div className="billing-facts"><span><Clock3 size={15}/>{business.subscriptionCurrentPeriodEnd?`Nächste Periode: ${new Date(business.subscriptionCurrentPeriodEnd).toLocaleDateString('de-DE')}`:business.trialEndsAt?`Testphase bis ${new Date(business.trialEndsAt).toLocaleDateString('de-DE')}`:'Keine Periode'}</span><span><CreditCard size={15}/> Friseur-Limit: {friseurLimitFor(business.billingPlan,business.subscriptionStatus)}</span></div>{business.stripeCustomerId&&<form method="post" action="/api/billing/portal"><button className="gold" type="submit"><ExternalLink size={16}/> Zahlungsportal öffnen</button></form>}</section>
 <section className="subscription-plans" aria-labelledby="subscription-plans-title"><div className="subscription-intro"><span className="eyebrow">PASSEND ZU DEINEM TEAM</span><h2 id="subscription-plans-title">Ein Tarif für jede Salongröße.</h2><p>Monatliche Abrechnung. Wähle die passende Anzahl an Friseur-Zugängen.</p><span className="subscription-frequency">Monatlich</span></div><div className="subscription-grid">{BILLING_PLANS.map(p=><section className={`subscription-card subscription-${p.key} ${business.billingPlan===p.key?'is-current':''}`} key={p.key} aria-label={`${p.name} Tarif`}><div className="subscription-ribbon">{p.key==='professional'?'Für dein Team':p.key==='business'?'Für große Teams':'Für deinen Start'}</div><div className="subscription-card-body"><div className="subscription-name"><h3>{p.name}</h3>{business.billingPlan===p.key&&<span>Aktueller Tarif</span>}</div><p className="subscription-description">{p.key==='starter'?'Digitale Kundentreue für deinen persönlichen Salonalltag.':p.key==='professional'?'Mehr Zugänge und Gestaltung für dein eingespieltes Team.':'Viel Platz für dein Team und einen wachsenden Betrieb.'}</p><div className="subscription-price"><strong>{p.monthlyLabel}</strong><span>/ Monat</span></div><p className="subscription-billing-note">Monatlich abgerechnet</p><div className="subscription-allowance">{p.friseurLimit===1?'1 Friseur-Zugang':`Bis zu ${p.friseurLimit} Friseur-Zugänge`}</div><ul className="subscription-features">{p.features.map(x=><li key={x}><Check size={17} aria-hidden="true"/><span>{x}</span></li>)}</ul><form className="subscription-action" method="post" action="/api/billing/checkout"><input type="hidden" name="plan" value={p.key}/><input type="hidden" name="interval" value="monthly"/><button className="subscription-select" type="submit" disabled={hasManagedSubscription}>{p.name} wählen</button></form></div></section>)}</div>{hasManagedSubscription&&<p className="subscription-footnote">Dein bestehendes Abonnement verwaltest du über das Zahlungsportal oben.</p>}<p className="subscription-footnote">Die kostenlose Testphase für neue Salons dauert 3 Tage.</p></section>

 </DashboardShell>
}
