import { requireManager } from '@/lib/auth';
import { getBusinessById } from '@/lib/store';
import { BILLING_PLANS,billingOperational,billingStatusLabel,friseurLimitFor,listBillingHistory,planDefinition,trialActive } from '@/lib/billing';
import { ArrowLeft,Check,Clock3,CreditCard,ExternalLink,ReceiptText,ShieldCheck } from 'lucide-react';
export const dynamic='force-dynamic';
export default async function BillingPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const s=await requireManager();const [business,history]=await Promise.all([getBusinessById(s.businessId!),listBillingHistory(s.businessId!,15)]);const q=await searchParams;if(!business)return null;
 const trialDays=business.trialEndsAt?Math.max(0,Math.ceil((new Date(business.trialEndsAt).getTime()-Date.now())/86400000)):0;const currentPlan=planDefinition(business.billingPlan);const operational=billingOperational(business);const hasManagedSubscription=!!business.stripeSubscriptionId&&!['canceled','incomplete_expired'].includes(business.subscriptionStatus);
 return <main><header className="topbar"><div className="brand"><img src="/icon.svg" alt="Rezix"/><div><b>REZIX</b><span>BILLING</span></div></div><a className="secondary link-button" href="/manager"><ArrowLeft size={15}/> Dashboard</a></header><div className="shell"><div className="page-title"><div><span className="eyebrow">ABONNEMENT & RECHNUNGEN</span><h1>Rezix Billing</h1><p>Verwalte den Tarif für {business.name}. Zahlungsdaten werden ausschließlich von Stripe verarbeitet.</p></div><div className={`billing-status ${operational?'ok':'warn'}`}><ShieldCheck size={16}/>{billingStatusLabel(business.subscriptionStatus)}</div></div>
 {q.checkout==='success'&&<div className="success">Checkout abgeschlossen. Stripe synchronisiert den Tarif über den Webhook. Falls der Status noch nicht aktualisiert ist, lade die Seite in wenigen Sekunden neu.</div>}{q.checkout==='cancelled'&&<div className="alert">Checkout wurde abgebrochen. Es wurde kein neuer Tarif aktiviert.</div>}{q.manage&&<div className="alert">Für ein bestehendes Abonnement verwende bitte das Stripe Kundenportal.</div>}{q.error&&<div className="alert">Billing-Aktion konnte nicht abgeschlossen werden ({q.error}). Prüfe Stripe-Konfiguration und Webhook.</div>}
 <section className="panel billing-current"><div><span className="eyebrow">AKTUELLER STATUS</span><h2>{business.billingPlan==='trial'?'Kostenlose Testphase':currentPlan?.name||business.billingPlan}</h2><p className="muted">{business.subscriptionStatus==='trialing'?(trialActive(business)?`Noch ${trialDays} Tag${trialDays===1?'':'e'} Testphase.`:'Die Testphase ist abgelaufen.'):`Status: ${billingStatusLabel(business.subscriptionStatus)}${business.cancelAtPeriodEnd?' · Kündigung zum Periodenende vorgemerkt':''}`}</p></div><div className="billing-facts"><span><Clock3 size={15}/>{business.subscriptionCurrentPeriodEnd?`Nächste Periode: ${new Date(business.subscriptionCurrentPeriodEnd).toLocaleDateString('de-DE')}`:business.trialEndsAt?`Trial bis ${new Date(business.trialEndsAt).toLocaleDateString('de-DE')}`:'Keine Periode'}</span><span><CreditCard size={15}/> Friseur-Limit: {friseurLimitFor(business.billingPlan,business.subscriptionStatus)}</span></div>{business.stripeCustomerId&&<form method="post" action="/api/billing/portal"><button className="gold" type="submit"><ExternalLink size={16}/> Stripe Kundenportal öffnen</button></form>}</section>
 <div className="billing-grid">{BILLING_PLANS.map(p=><section className={`plan-card ${business.billingPlan===p.key?'selected':''}`} key={p.key}><div><span className="eyebrow">{p.name.toUpperCase()}</span><h2>{p.monthlyLabel}<small>/Monat</small></h2><p className="muted">oder {p.yearlyLabel}/Jahr</p></div><div className="plan-features">{p.features.map(x=><span key={x}><Check size={15}/>{x}</span>)}</div><div className="plan-actions"><form method="post" action="/api/billing/checkout"><input type="hidden" name="plan" value={p.key}/><input type="hidden" name="interval" value="monthly"/><button className="gold full" type="submit" disabled={hasManagedSubscription}>Monatlich wählen</button></form><form method="post" action="/api/billing/checkout"><input type="hidden" name="plan" value={p.key}/><input type="hidden" name="interval" value="yearly"/><button className="secondary full" type="submit" disabled={hasManagedSubscription}>Jährlich wählen</button></form></div></section>)}</div>
 <section className="panel quick"><h2><ReceiptText size={20}/> Billing-Verlauf</h2>{history.length===0?<div className="empty-block"><ReceiptText size={32}/><b>Noch keine Stripe-Ereignisse</b><span>Nach dem ersten Checkout erscheinen Zahlungen und Statusänderungen hier.</span></div>:<div className="attention">{history.map((h:any,i:number)=><div className="row" key={`${h.created_at}-${i}`}><div className="avatar sm"><ReceiptText size={15}/></div><div><b>{String(h.event_type)}</b><span>{new Date(h.created_at).toLocaleString('de-DE')} · {h.subscription_status||'—'} {h.amount_total!=null?`· ${(Number(h.amount_total)/100).toFixed(2)} ${String(h.currency||'').toUpperCase()}`:''}</span></div></div>)}</div>}</section>
 </div></main>
}
