import { NextResponse } from 'next/server';
import { currentSession } from '@/lib/auth';
import { businessSlugExists, createBusinessWithManager, normalizeSlug, staffEmailExists } from '@/lib/store';
import { uploadSalonAsset } from '@/lib/storage';
import { audit,sameOrigin,escapeHtml } from '@/lib/security';
import { createOneTimeToken } from '@/lib/auth-store';
import { appBaseUrl,sendAuthEmail } from '@/lib/mailer';
export const runtime='nodejs';
export async function POST(req:Request){if(!sameOrigin(req))return NextResponse.json({error:'Invalid origin'},{status:403});const s=await currentSession();if(!s||s.role!=='admin')return NextResponse.redirect(new URL('/admin/login',req.url),303);const f=await req.formData();const name=String(f.get('name')||'').trim().slice(0,120);const slug=normalizeSlug(String(f.get('slug')||''));const rewardTarget=Number(f.get('rewardTarget'));const rewardText=String(f.get('rewardText')||'').trim().slice(0,160);const managerName=String(f.get('managerName')||'').trim().slice(0,100);const managerEmail=String(f.get('managerEmail')||'').trim().toLowerCase().slice(0,160);const managerPassword=String(f.get('managerPassword')||'');const logo=f.get('logo');const stamp=f.get('stamp');if(!name||!slug||!rewardText||!managerName||!managerEmail.includes('@')||managerPassword.length<12||!Number.isInteger(rewardTarget)||rewardTarget<2||rewardTarget>30||!(logo instanceof File)||logo.size===0||logo.size>2_000_000||!(stamp instanceof File)||stamp.size===0||stamp.size>2_000_000)return NextResponse.redirect(new URL('/admin/new-salon?error=1',req.url),303);if(await businessSlugExists(slug)||await staffEmailExists(managerEmail))return NextResponse.redirect(new URL('/admin/new-salon?error=1',req.url),303);let logoUrl:string|null=null,stampUrl:string|null=null;try{[logoUrl,stampUrl]=await Promise.all([uploadSalonAsset(logo,`${slug}/logo`),uploadSalonAsset(stamp,`${slug}/stamp`)]);}catch(e){console.error(e);return NextResponse.redirect(new URL('/admin/new-salon?upload=1',req.url),303)}try{const created=await createBusinessWithManager({name,slug,rewardTarget,rewardText,logoUrl,stampUrl,managerName,managerEmail,managerPassword});const token=await createOneTimeToken(created.managerId,'manager','email_verify',1440);const verifyUrl=`${appBaseUrl(req)}/api/auth/verify-email?token=${encodeURIComponent(token)}`;const emailSent=await sendAuthEmail({to:managerEmail,subject:'Rezix – Manager E-Mail bestätigen',html:`<h2>Willkommen bei Rezix</h2><p>Dein Manager-Zugang für <b>${escapeHtml(name)}</b> wurde erstellt.</p><p><a href="${verifyUrl}">E-Mail bestätigen</a></p><p>Der Link ist 24 Stunden gültig.</p>`});await audit({session:s,businessId:created.businessId,action:'business.created',targetType:'business',targetId:created.businessId,req,metadata:{name,slug,managerEmail,emailSent}});return NextResponse.redirect(new URL(`/admin/new-salon?created=1${emailSent?'':'&mailError=1'}`,req.url),303)}catch(e){console.error(e);return NextResponse.redirect(new URL('/admin/new-salon?error=1',req.url),303)}}
